
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <div class="widget">
                <div class="widget-title">
                    <h4><i class="icon-reorder"></i>Report-View</h4>
                    <span class="tools"> <a href="javascript:;" class="icon-chevron-down"></a> </span> </div>
                <div class="widget-body">
                    <div id="reportengine_div" name="reportengine_div" class="form-horizontal">
                        <div id="div_loading" class="loader1" style="display:none"> Data will be under processing </div>
                        <form>
                            <div class="control-group">
                                <label class="control-label">Reports </label>
                                <div class="controls">
                                    <input type="hidden" name="page" id="page" value="1">
                                    <?php
                                    ?>
                                    <select id="reportname" name="reportname" onchange="getreportfilter(this.value);">
                                        <option>Select Report </option>
                                        <?php
                                        foreach ($this->_reportDetails as $root => $rootData) {
                                            foreach ($rootData as $module => $moduleData) {
                                                echo '<optgroup label="' . "    " . $module . '">';
                                                foreach ($moduleData as $reportData) {
                                                    echo '<option value="' . $reportData['id'] . '"> ' . $reportData['name'] . ' </option>';
                                                }
                                                echo '</optgroup>';
                                            }
                                            ;
                                        }
                                        ?>
                                    </select>
                                </div>
                            </div>
                            <div id="filterdiv" name="filterdiv"></div>
                            <div class="form-actions">
                                <button type="button" class="btn btn-success" id="report_submit" name="report_submit" onclick="return reportdatasubmit();"><i class="icon-ok icon-white"></i> Submit </button>
                            </div>
                        </form>
                        <div id="reportoutput_div" name="reportoutput_div"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
