<div class="control-group">
	<label class="control-label">Output Type</label>

		<div id="value_output_type" name="value_output_type">
			<div class="controls">
				<select id="output_type" class="chosen-with-diselect" tabindex="-1" name="output_type" onchange="disablerpp(this.value);">
				<option value="html" selected=""> On Display </option>
				<option value="csv"> CSV </option>
				<option value="pdf"> PDF </option>

				</select>
			</div>
		</div>
	</div>
	<div class="control-group" id="row_rpp">
		<label class="control-label">Records Per Page</label>

		<div id="value_rpp" name="value_rpp">
			<div class="controls">
				<select id="rpp" name="rpp" onchange="reportdatasubmit();">
					<option value=""> ALL </option>
					<option value="10"> 10 </option>
					<option value="15"> 15 </option>
					<option value="25"> 25 </option>
					<option value="50"> 50 </option>
					<option value="100"> 100 </option>
					<option value="250"> 250 </option>
					<option value="500"> 500 </option>
				</select>
			</div>
		</div>
	</div>