<div class="delivary-date">
    <form class="form-inline">
       <div class="form-group">
         <label for="exampleInputName2">Orderdate:</label>
             <select class="" id="">
               <option value="">Today</option>
               <option value="">tomorrow</option>
             </select>
       </div>
       <div class="form-group">
         <select class="" id="">
           <option value="">2:00PM</option>
           <option value="">2:00PM</option>
           <option value="">2:00PM</option>
           <option value="">2:00PM</option>
           <option value="">2:00PM</option>
         </select>
       </div>
     </form>  	
 </div>