<?php $wp = $this->_websiteSettings; ?>
<ul id="todaydeals">
    <li>
        <div class="col-md-12 right-padding"> <a href="<?php echo $wp->websiteUrl;  ?>ec_product/view"> <img src="<?php echo $wp->websiteUrl ?>img/images/products/carrot.png" />
                <div class="product-label"> <span class="sale-product-icon">-30%</span> </div>
                <div class="row product-info">
                    <p class="product-title">Carrot Product</p>
                    <div id="stars-existing" class="starrr" data-rating='4'></div>
                    <div class="row product-qnty">
                        <select name="product_all_qnty" id="product_all_qnty">
                            <option>1kg - 60.00</option>
                            <option>2kg - 110.00</option>
                            <option>3kg - 145.00</option>
                        </select>
                    </div>
                    <p class="product-price"> <span class="pt-price"><i class="fa fa-inr" aria-hidden="true"></i>500.00</span> <span class="offer-price price"><i class="fa fa-inr" aria-hidden="true"></i>450.00</span> </p>
                </div>
            </a> <a href="javascript:void(0)" title="Quick view" data-toggle="modal" data-target="#quickview"  class="quick-view-handler">Quick view</a>
            <div class="row product-btn-action">
                <button type="button" class="add-cart" name="btn_cart" id="btn_cart" title="Add To Cart"><i class="fa fa-shopping-cart" aria-hidden="true"></i>Add To Cart</button>
                <button type="button" class="link-btn" title="Add to Wishlist" name="btn_wishlist" id="btn_wishlist"><i class="fa fa-heart" aria-hidden="true"></i></button>
                <button type="button" title="view" class="link-btn" name="btn_view" id="btn_view"><i class="fa fa-eye" aria-hidden="true"></i></button>
            </div>
        </div>
    </li>
    <li>
        <div class="col-md-12 right-padding"> <a href="<?php echo $wp->websiteUrl;  ?>ec_product/view"> <img src="<?php echo $wp->websiteUrl ?>img/images/products/pber.png" />
                <div class="product-label"> <span class="sale-product-icon">-30%</span> </div>
                <div class="row product-info">
                    <p class="product-title">Carrot Product</p>
                    <div id="stars-existing" class="starrr" data-rating='4'></div>
                    <div class="row product-qnty">
                        <select name="product_all_qnty" id="product_all_qnty">
                            <option>1kg - 60.00</option>
                            <option>2kg - 110.00</option>
                            <option>3kg - 145.00</option>
                        </select>
                    </div>
                    <p class="product-price"> <span class="pt-price"><i class="fa fa-inr" aria-hidden="true"></i>500.00</span> <span class="offer-price price"><i class="fa fa-inr" aria-hidden="true"></i>450.00</span> </p>
                </div>
            </a> <a href="javascript:void(0)" title="Quick view" data-toggle="modal" data-target="#quickview"  class="quick-view-handler">Quick view</a>
            <div class="row product-btn-action">
                <button type="button" class="add-cart" name="btn_cart" id="btn_cart" title="Add To Cart"><i class="fa fa-shopping-cart" aria-hidden="true"></i>Add To Cart</button>
                <button type="button" class="link-btn" title="Add to Wishlist" name="btn_wishlist" id="btn_wishlist"><i class="fa fa-heart" aria-hidden="true"></i></button>
                <button type="button" title="view" class="link-btn" name="btn_view" id="btn_view"><i class="fa fa-eye" aria-hidden="true"></i></button>
            </div>
        </div>
    </li>
    <li>
        <div class="col-md-12 right-padding"> <a href="<?php echo $wp->websiteUrl;  ?>ec_product/view"> <img src="<?php echo $wp->websiteUrl ?>img/images/products/pineapple.png" />
                <div class="product-label"> <span class="sale-product-icon">-30%</span> </div>
                <div class="row product-info">
                    <p class="product-title">Carrot Product</p>
                    <div id="stars-existing" class="starrr" data-rating='4'></div>
                    <div class="row product-qnty">
                        <select name="product_all_qnty" id="product_all_qnty">
                            <option>1kg - 60.00</option>
                            <option>2kg - 110.00</option>
                            <option>3kg - 145.00</option>
                        </select>
                    </div>
                    <p class="product-price"> <span class="pt-price"><i class="fa fa-inr" aria-hidden="true"></i>500.00</span> <span class="offer-price price"><i class="fa fa-inr" aria-hidden="true"></i>450.00</span> </p>
                </div>
            </a> <a href="javascript:void(0)" title="Quick view" data-toggle="modal" data-target="#quickview"  class="quick-view-handler">Quick view</a>
            <div class="row product-btn-action">
                <button type="button" class="add-cart" name="btn_cart" id="btn_cart" title="Add To Cart"><i class="fa fa-shopping-cart" aria-hidden="true"></i>Add To Cart</button>
                <button type="button" class="link-btn" title="Add to Wishlist" name="btn_wishlist" id="btn_wishlist"><i class="fa fa-heart" aria-hidden="true"></i></button>
                <button type="button" title="view" class="link-btn" name="btn_view" id="btn_view"><i class="fa fa-eye" aria-hidden="true"></i></button>
            </div>
        </div>
    </li>
    <li>
        <div class="col-md-12 right-padding"> <a href="<?php echo $wp->websiteUrl;  ?>ec_product/view"> <img src="<?php echo $wp->websiteUrl ?>img/images/products/broccoli.png" />
                <div class="product-label"> <span class="sale-product-icon">-30%</span> </div>
                <div class="row product-info">
                    <p class="product-title">Carrot Product</p>
                    <div id="stars-existing" class="starrr" data-rating='4'></div>
                    <div class="row product-qnty">
                        <select name="product_all_qnty" id="product_all_qnty">
                            <option>1kg - 60.00</option>
                            <option>2kg - 110.00</option>
                            <option>3kg - 145.00</option>
                        </select>
                    </div>
                    <p class="product-price"> <span class="pt-price"><i class="fa fa-inr" aria-hidden="true"></i>500.00</span> <span class="offer-price price"><i class="fa fa-inr" aria-hidden="true"></i>450.00</span> </p>
                </div>
            </a> <a href="javascript:void(0)" title="Quick view" data-toggle="modal" data-target="#quickview"  class="quick-view-handler">Quick view</a>
            <div class="row product-btn-action">
                <button type="button" class="add-cart" name="btn_cart" id="btn_cart" title="Add To Cart"><i class="fa fa-shopping-cart" aria-hidden="true"></i>Add To Cart</button>
                <button type="button" class="link-btn" title="Add to Wishlist" name="btn_wishlist" id="btn_wishlist"><i class="fa fa-heart" aria-hidden="true"></i></button>
                <button type="button" title="view" class="link-btn" name="btn_view" id="btn_view"><i class="fa fa-eye" aria-hidden="true"></i></button>
            </div>
        </div>
    </li>
    <li>
        <div class="col-md-12 right-padding"> <a href="<?php echo $wp->websiteUrl;  ?>ec_product/view"> <img src="<?php echo $wp->websiteUrl ?>img/images/products/carrot.png" />
                <div class="product-label"> <span class="sale-product-icon">-30%</span> </div>
                <div class="row product-info">
                    <p class="product-title">Carrot Product</p>
                    <div id="stars-existing" class="starrr" data-rating='4'></div>
                    <div class="row product-qnty">
                        <select name="product_all_qnty" id="product_all_qnty">
                            <option>1kg - 60.00</option>
                            <option>2kg - 110.00</option>
                            <option>3kg - 145.00</option>
                        </select>
                    </div>
                    <p class="product-price"> <span class="pt-price"><i class="fa fa-inr" aria-hidden="true"></i>500.00</span> <span class="offer-price price"><i class="fa fa-inr" aria-hidden="true"></i>450.00</span> </p>
                </div>
            </a> <a href="javascript:void(0)" title="Quick view" data-toggle="modal" data-target="#quickview"  class="quick-view-handler">Quick view</a>
            <div class="row product-btn-action">
                <button type="button" class="add-cart" name="btn_cart" id="btn_cart" title="Add To Cart"><i class="fa fa-shopping-cart" aria-hidden="true"></i>Add To Cart</button>
                <button type="button" class="link-btn" title="Add to Wishlist" name="btn_wishlist" id="btn_wishlist"><i class="fa fa-heart" aria-hidden="true"></i></button>
                <button type="button" title="view" class="link-btn" name="btn_view" id="btn_view"><i class="fa fa-eye" aria-hidden="true"></i></button>
            </div>
        </div>
    </li>
    <li>
        <div class="col-md-12 right-padding"> <a href="<?php echo $wp->websiteUrl;  ?>ec_product/view"> <img src="<?php echo $wp->websiteUrl ?>img/images/products/beetroot.png" />
                <div class="product-label"> <span class="sale-product-icon">-30%</span> </div>
                <div class="row product-info">
                    <p class="product-title">Carrot Product</p>
                    <div id="stars-existing" class="starrr" data-rating='4'></div>
                    <div class="row product-qnty">
                        <select name="product_all_qnty" id="product_all_qnty">
                            <option>1kg - 60.00</option>
                            <option>2kg - 110.00</option>
                            <option>3kg - 145.00</option>
                        </select>
                    </div>
                    <p class="product-price"> <span class="pt-price"><i class="fa fa-inr" aria-hidden="true"></i>500.00</span> <span class="offer-price price"><i class="fa fa-inr" aria-hidden="true"></i>450.00</span> </p>
                </div>
            </a> <a href="javascript:void(0)" title="Quick view" data-toggle="modal" data-target="#quickview"  class="quick-view-handler">Quick view</a>
            <div class="row product-btn-action">
                <button type="button" class="add-cart" name="btn_cart" id="btn_cart" title="Add To Cart"><i class="fa fa-shopping-cart" aria-hidden="true"></i>Add To Cart</button>
                <button type="button" class="link-btn" title="Add to Wishlist" name="btn_wishlist" id="btn_wishlist"><i class="fa fa-heart" aria-hidden="true"></i></button>
                <button type="button" title="view" class="link-btn" name="btn_view" id="btn_view"><i class="fa fa-eye" aria-hidden="true"></i></button>
            </div>
        </div>
    </li>
    <li>
        <div class="col-md-12 right-padding"> <a href="<?php echo $wp->websiteUrl;  ?>ec_product/view"> <img src="<?php echo $wp->websiteUrl ?>img/images/products/broccoli.png" />
                <div class="product-label"> <span class="sale-product-icon">-30%</span> </div>
                <div class="row product-info">
                    <p class="product-title">Carrot Product</p>
                    <div id="stars-existing" class="starrr" data-rating='4'></div>
                    <div class="row product-qnty">
                        <select name="product_all_qnty" id="product_all_qnty">
                            <option>1kg - 60.00</option>
                            <option>2kg - 110.00</option>
                            <option>3kg - 145.00</option>
                        </select>
                    </div>
                    <p class="product-price"> <span class="pt-price"><i class="fa fa-inr" aria-hidden="true"></i>500.00</span> <span class="offer-price price"><i class="fa fa-inr" aria-hidden="true"></i>450.00</span> </p>
                </div>
            </a> <a href="javascript:void(0)" title="Quick view" data-toggle="modal" data-target="#quickview"  class="quick-view-handler">Quick view</a>
            <div class="row product-btn-action">
                <button type="button" class="add-cart" name="btn_cart" id="btn_cart" title="Add To Cart"><i class="fa fa-shopping-cart" aria-hidden="true"></i>Add To Cart</button>
                <button type="button" class="link-btn" title="Add to Wishlist" name="btn_wishlist" id="btn_wishlist"><i class="fa fa-heart" aria-hidden="true"></i></button>
                <button type="button" title="view" class="link-btn" name="btn_view" id="btn_view"><i class="fa fa-eye" aria-hidden="true"></i></button>
            </div>
        </div>
    </li>
</ul>
<script>
    require(['config'], function () {
        require(['jquery', 'scrollproducts'], function ($) {
            $("#todaydeals").flexisel({
                visibleItems: 3,
                itemsToScroll: 3,
                autoPlay: {
                    enable: false,
                    interval: 5000,
                    pauseOnHover: true
                }
            });
        });
    });
</script>