<div class="row">
    <div class="col-md-12"> 
        <div class="row vendor_according">    
            <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                <div class="panel panel-default">
                    <div class="panel-heading" role="tab" id="headingOne">
                        <h4 class="panel-title">
                            Product List                                 
                            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#product_list" aria-expanded="true" aria-controls="collapseOne">
                           <span class="glyphicon glyphicon-plus pull-right" aria-hidden="true"></span> </a>
                        </h4>
                    </div>
                    <div id="product_list" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                        <div class="panel-body">
                            <div id="order-tables-order">
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th class="obs-width">Image</th>
                                            <th class="obs-width">Product Name</th>
                                            <th class="obs-width">Payment Mode</th>
                                            <th class="obs-width">Total Amount</th>
                                            <th class="obs-width">Dispatched</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td data-title="Image" class="prd-image"><img src="images/carrot.jpg" class="img-responsive"></td>
                                            <td data-title="Product Name">Carrot</td>
                                            <td data-title="Payment Mode" class="numeric">-----</td>
                                            <td data-title="Total Amount" class="numeric">Rs.10,000</td>
                                            <td data-title="Dispatched" class="numeric">----</td>
                                        </tr>
                                    </tbody>
                                </table>
                                <div class="col-sm-offset-6 col-sm-6">
                                    <button type="button" class="btn btn-primary button-overall">View All</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>    


