<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Description of CoreUrlRewrite
 *
 * @author venkatesh
 */
  namespace Core\Modules\CoreDevelopmentsettings\Setup;
class CoreUrlRewrite 
{
    //put your code here
    function execute()
    {
        $cc = new \CoreClass();         $setup=$cc->getObject("\Core\DataBase\Setup");  
        $setup->setTable("core_url_rewrite");
        if(!$setup->tableExists($setup->getTable()))
        {
            $setup->setDisplayValue("Url Redirection");
            $setup->addColumnName(array(
                "name"=>"id",
                "displayValue"=>"Url Id",                
                "type"=>"bigint",
                "size"=>"17",
                "key"=>"primary",
                "auto_increment"=>1,           
            ));
            $setup->addColumnName(array(
                "name"=>"core_registernode_id",
                "displayValue"=>"Node Name",            
                "default"=>NULL,                
                "type"=>"varchar",
                "size"=>"255"          
            ));
            $setup->addColumnName(array(
                "name"=>"primary_id",
                "displayValue"=>"Primary Id",            
                "default"=>false,
                "type"=>"longtext"     
            ));
            $setup->addColumnName(array(
                "name"=>"request_path",
                "displayValue"=>"Request Path",            
                "default"=>NULL,                
                "type"=>"varchar",
                "size"=>"255"          
            ));
            $setup->addColumnName(array(
                "name"=>"target_path",
                "displayValue"=>"Target Path",            
                "default"=>NULL,                
                "type"=>"varchar",
                "size"=>"255"          
            ));
            $setup->addColumnName(array(
                "name"=>"description",
                "displayValue"=>"Description",            
                "default"=>NULL,                
                "type"=>"text"        
            ));
            $setup->addColumnName(array(
                "name"=>"is_autogenerated",
                "displayValue"=>"Is rewrite generated automatically flag",            
                "default"=>NULL,
                "type"=>"tinyint",
                "size"=>"1",                
            ));
            
            $setup->addColumnName(array(
                "name"=>"metadata",
                "displayValue"=>"Metadata",            
                "default"=>NULL,                
                "type"=>"text"        
            ));
            $setup->addColumnName(array(
                "name"=>"createdby",
                "displayValue"=>"Created User Id",            
                "default"=>NULL,
                "type"=>"int",
                "size"=>"11",                
            ));
             $setup->addColumnName(array(
                "name"=>"createdat",
                "displayValue"=>"Created Datetime",            
                "default"=>NULL,
                "type"=>"datetime"
            ));
            $setup->addColumnName(array(
                "name"=>"updatedby",
                "displayValue"=>"Updated User Id",            
                "default"=>NULL,
                "type"=>"int",
                "size"=>"11",                
            ));
            $setup->addColumnName(array(
                "name"=>"updatedat",
                "displayValue"=>"Updated Datetime",            
                "default"=>NULL,
                "type"=>"datetime"
            ));
             $setup->create();
        }
    }
}
