<?php 
$wp = $this->_websiteSettings; 
$productList = $this->getWishList();
?>
<!-- contant part -->
<div class="row">
    <section class="row" id="container-block">
        <section class="row">       
            <!-- Page navogation part -->
            <div class="container">
                <div class="page-navigation">
                    <ul class="breadcrumbs">
                        <li> <a href="javascript:void(0)">Home</a> </li>
                        <li> <a href="javascript:void(0)">Account</a> </li>
                        <li> <a href="javascript:void(0)">Wishlist</a> </li>
                    </ul>
                </div>
            </div>
        </section>
        <section class="row account-info">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 col-md-12">
                        <?php $this->loadChildBlock("usermenu"); ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12">
                        <div class="row innerWrapper">
                            <h1 class="block-title">Wishlist</h1>
                            <table class="table table-responsive wish-list">
                                <thead>
                                    <tr>
                                        <th style="width:20%">Product image</th>
                                        <th style="width:25%">Product Name</th>
                                        <th style="width:25%">Unit price</th>
                                        <th style="width:10%" class="delete">&nbsp;</th>
                                        <th style="width:25%" class="checkout">&nbsp;</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <th ><img src="<?php echo $wp->websiteUrl; ?>img/images/items/Carrot.png" class="img-responsive"></th>
                                        <td>Carrot</td>          
                                        <td>RS40</td>
                                        <td><i class="fa fa-trash" aria-hidden="true"></i></td>              
                                        <td><a href="">Checkout</a></td>    
                                    </tr>
                                    <tr>
                                        <th ><img src="<?php echo $wp->websiteUrl ?>img/images/items/Carrot.png" class="img-responsive"></th>
                                        <td>Carrot</td>          
                                        <td>RS40</td>
                                        <td><i class="fa fa-trash" aria-hidden="true"></i></td>              
                                        <td><a href="">Checkout</a></td>    
                                    </tr>
                                    <tr>
                                        <th ><img src="<?php echo $wp->websiteUrl ?>img/images/items/Carrot.png" class="img-responsive"></th>
                                        <td>Carrot</td>          
                                        <td>RS40</td>
                                        <td><i class="fa fa-trash" aria-hidden="true"></i></td>              
                                        <td><a href="">Checkout</a></td>    
                                    </tr>
                                    <tr>
                                        <th ><img src="<?php echo $wp->websiteUrl ?>img/images/items/Carrot.png" class="img-responsive"></th>
                                        <td>Carrot</td>          
                                        <td>RS40</td>
                                        <td><i class="fa fa-trash" aria-hidden="true"></i></td>              
                                        <td><a href="">Checkout</a></td>    
                                    </tr>
                                    <tr>
                                        <th ><img src="<?php echo $wp->websiteUrl ?>img/images/items/Carrot.png" class="img-responsive"></th>
                                        <td>Carrot</td>          
                                        <td>RS40</td>
                                        <td><i class="fa fa-trash" aria-hidden="true"></i></td>              
                                        <td><a href="">Checkout</a></td>    
                                    </tr>
                                    <tr>
                                        <th ><img src="<?php echo $wp->websiteUrl ?>img/images/items/Carrot.png" class="img-responsive"></th>
                                        <td>Carrot</td>          
                                        <td>RS40</td>
                                        <td><i class="fa fa-trash" aria-hidden="true"></i></td>              
                                        <td><a href="">Checkout</a></td>    
                                    </tr>
                                    <tr>
                                        <th ><img src="<?php echo $wp->websiteUrl ?>img/images/items/Carrot.png" class="img-responsive"></th>
                                        <td>Carrot</td>          
                                        <td>RS40</td>
                                        <td><i class="fa fa-trash" aria-hidden="true"></i></td>              
                                        <td><a href="">Checkout</a></td>    
                                    </tr>

                                </tbody>
                            </table>         
                        </div>
                    </div>
                    <!--/row end--> 
                </div>
            </div>
        </section>
    </section>
</div>
<!-- End contant part --> 
