<?php $wp = $this->_websiteSettings; ?>
<!-- Customer Profile -->
<div class="row">
    <section class="row" id="container-block">
        <section class="row">       
            <!-- Page navigation part -->
            <div class="container">
                <div class="page-navigation">
                    <ul class="breadcrumbs">
                        <li> <a href="javascript:void(0)">Home</a> </li>
                        <li> <a href="javascript:void(0)">Account</a> </li>
                        <li> <a href="javascript:void(0)">User Profile</a> </li>
                    </ul>
                </div>
            </div>
        </section>
        <section class="row account-info">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 col-md-12">
                        <?php $this->loadChildBlock("usermenu"); ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12">
                        <div class="row innerWrapper">
                            <h1 class="block-title">Loacation Details</h1>
                            <div class="row __web-inspector-hide-shortcut__">
                                <div class="col-xs-12 col-sm-12">
                                    <h2 class="block-title"><span>Locations Assigned</span>
                                    </h2>
                                    <!--location-details-->
                                    <div class="row innerWrapper account-order">
                                        
                               <div class="table-responsive border">
                            <table class="table table-bordered">
                                <thead>
                                  <tr>
                                    <th class="col-xs-2">S.No</th>
                                    <th class="col-xs-3">Date</th>
                                    <th class="col-md-1 hidden-xs hidden-sm">Area</th>
                                    <th class="col-xs-2">Location</th>
                                    <th class="col-xs-3">Address</th>
                                    <th class="col-xs-1">Contact No.</th>
                                </tr>
								</thead>
                                <tbody>
                                    
                                    
                                    
   <tr>
      <th scope="row">1</th>
      <td>12/03/2017</td>
      <td>Area 1</td>
      <td>Filmnagar</td>
      <td>H-No.1-109,
      Area1,Filmnagar</td>
      <td>9010306582</td>
    </tr>
      <tr>
             <td><a href="">2</a></td>
              <td>12th August 2016</td>
               <td class="hidden-xs hidden-sm">Area 2</td>
               <td>Banjarahills</td>
                <td>H-No.1-109,Area 2,Banjarahills</td>
                <td>9023306582</td>
           </tr>
                                <tr>
             <td><a href="">3</a></td>
              <td>15th June 2015</td>
               <td class="hidden-xs hidden-sm">Area 3</td>
               <td>Panjagutta</td>
                <td>H-No.36-109,Area 3,Panjagutta</td>
                <td>8010306582</td>
           </tr>
                                  <tr>
             <td><a href="">4</a></td>
              <td>26th Feb 2015</td>
               <td class="hidden-xs hidden-sm">Area 4</td>
               <td>Ameerpet</td>
                <td>H-No.102-109,Area 4,Ameerpet</td>
                <td>9010306582</td>
           </tr>
                                  <tr>
             <td><a href="">5</a></td>
              <td>12th July 2015</td>
               <td class="hidden-xs hidden-sm">Area 1</td>
               <td>Filmnagar</td>
                <td>H-No.1-109,Area 5 ,Filmnagar</td>
                <td>9010306582</td>
           </tr>
                                 <tr>
             <td><a href="">6</a></td>
              <td>12th July 2015</td>
               <td class="hidden-xs hidden-sm">Area 6</td>
               <td>Filmnagar</td>
                <td>H-No.1-109,Area 6,Filmnagar</td>
                <td>9010306582</td>
           </tr>
                            </tbody></table>
                        </div>                                    
                                        
                                        
                                    </div>
                                    <div class="clear clearfix"></div>
                                </div>
                            </div>    

                        </div>
                        <!--/row end--> 

                    </div>
                </div>
            </div>
        </section>
    </section>
</div>
<!-- End contant part --> 