<?php
$wp = $this->_websiteSettings;
$session = new \Core\Session();
$sessionData = $session->getFrontendSession();
$customerId = $sessionData['profileId'];
$customerData = $this->getcutomerData($customerId);
?>
<!-- Customer Profile -->
<div class="row">
    <section class="row" id="container-block">
        <section class="row">       
            <!-- Page navogation part -->
            <div class="container">
                <div class="page-navigation">
                    <ul class="breadcrumbs">
                        <li> <a href="javascript:void(0)">Home</a> </li>
                        <li> <a href="javascript:void(0)">Account</a> </li>
                        <li> <a href="javascript:void(0)">User Profile</a> </li>
                    </ul>
                </div>
            </div>
        </section>
        <section class="row account-info">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 col-md-12">
                        <?php $this->loadChildBlock("usermenu"); ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12">
                        <div class="row innerWrapper">
                            <h1 class="block-title">Profile</h1>
                            <div class="col-md-2">
                                <img src="<?php echo $wp->websiteUrl; ?>img/images/person.png" class="img-responsive">
                                <div class="form-group">
                                  
                                    <input type="file" id="exampleInputFile">				
                                </div>
                            </div> 
                            <div class="col-md-10 col-sm-6 col-xs-12"> 
                                <div class=" basic-form">
                                    <form class="form-horizontal" id="FormProfile">                             
                                        <div class="form-group">
                                            <label for="firstname" class="col-sm-2 control-label">First Name</label>
                                            <div class="col-sm-10">
                                                <input type="text" class="form-control" id="pro_fisrt_name" name="pro_fisrt_name" placeholder="First Name" value="<?Php echo $customerData['first_name'] ?>">
                                                <span class="error" id="error_pro_fisrt_name" style="display: none;"></span> </div></div>
                                        <div class="form-group">
                                            <label for="lastname" class="col-sm-2 control-label">Last Name</label>
                                            <div class="col-sm-10">
                                                <input type="text" class="form-control" id="pro_last_name" name="pro_last_name" placeholder="Last Name" value="<?Php echo $customerData['last_name'] ?>">
                                                <span class="error" id="error_pro_last_name" style="display: none;"></span> </div></div>
                                        <div class="form-group">
                                            <label for="phone" class="col-sm-2 control-label">Phone</label>
                                            <div class="col-sm-10">
                                                <input type="text" class="form-control" id="pro_phone" name="pro_phone" placeholder="Phone Name" value="<?Php echo $customerData['phone_number'] ?>">
                                                <span class="error" id="error_pro_phone" style="display: none;"></span> </div></div>
                                        <div class="form-group">
                                            <label for="email" class="col-sm-2 control-label">Email</label>
                                            <div class="col-sm-10">
                                                <input type="text" class="form-control" id="pro_email" name="pro_email" placeholder="Address" value="<?Php echo $customerData['email'] ?>">
                                                <span class="error" id="error_pro_email" style="display: none;"></span> </div> </div>
                                                 <div class="form-group">
                                            <label for="email" class="col-sm-2 control-label">Password</label>
                                            <div class="col-sm-10">
                                                <input type="text" class="form-control" id="pro_boy_password" name="pro_boy_password" placeholder="password" value="<?Php echo $customerData['email'] ?>">
                                                <span class="error" id="error_pro_boy_password" style="display: none;"></span> </div> </div>
                                                 <div class="form-group">
                                            <label for="email" class="col-sm-2 control-label">Change Password</label>
                                            <div class="col-sm-10">
                                                <input type="text" class="form-control" id="pro_boy_chng_password" name="pro_boy_chng_password" placeholder="Change password" value="<?Php echo $customerData['email'] ?>">
                                                <span class="error" id="error_pro_boy_chng_password" style="display: none;"></span> </div> </div>
                                        <div class="form-group">
                                            <div class="col-sm-offset-2 col-sm-10">
                                                <button type="button" class="btn btn-default pull-right" onclick="(function() {require('Customer/customer').cutomerProfileUpdate() })()">Save Info</button>
                                            </div>
                                        </div>
                              </form>
                                </div>          
                            </div>
                        </div>
                        <!--/row end--> 

                    </div>
                </div>
             
        </section>
    </section>
</div>
<!-- End contant part --> 