<?php
    if($this->_action=='admin')
    {
        echo $this->_Value;
    }
    else
    {
        if($this->_readonly)
        {
            $type="hidden";
        }
        else
        {
            $type="type";
        }
    ?>    
    <?php
        if($this->_readonly)
        {
            ?>
            <input class="input-large" type="<?php echo $type; ?>" id="<?php echo $this->_idName; ?>" name="<?php echo $this->_idName; ?>" value="<?php echo $this->_Value;?>" placeholder="<?php echo $this->getLabel($this->_idName); ?>" onchange="<?php echo $this->_onchange; ?>" <?php echo $this->_required; ?> />
            <?php
            echo '<span class="text_display">'.$this->_Value."</span>";
        }
        else
        {
            ?>
            <div class="input-prepend input-append"><input class="input-large" type="text" id="<?php echo $this->_idName; ?>" name="<?php echo $this->_idName; ?>" value="<?php echo $this->_Value;?>" placeholder="<?php echo $this->getLabel($this->_idName); ?>" <?php echo $this->_required; ?> onchange="return formvalidations(this.value,'<?php echo $this->_idName; ?>','PHN');<?php echo $this->_onchange; ?>"><span class="add-on"><i class="icon-phone"></i><span id="status_<?php echo $this->_idName; ?>"></span></span></div>
            <?php
            
        }
    }
?>