<?php

if($this->_action=='admin' || $this->_action=='adminRefresh')
{    
    echo $this->_Value;
}
else 
{

    if($this->_readonly=='1')
    {
            
            $displayValue=Core::getValueFromArray(Core::getValueFromArray($this->_options,0),'pds');
            ?>
            <input type="hidden" id="<?php echo $this->_idName; ?>" name="<?php echo $this->_idName; ?>" value="<?php echo $this->_Value; ?>" /> <span class="text_display" ><?php echo $displayValue;?> </span>
            <?php

            if($this->_onchange)
            {
            ?>
            <script>
                <?php echo $this->_onchange; ?>
            </script>

            <?php
            }
    }           
    else
    {
            ?>
            <select  id="<?php echo $this->_idName; ?>" name="<?php echo $this->_idName; ?>" onchange="<?php echo $this->_onchange; ?>" >
       <option value="">  Select <?php echo $this->getLabel($this->_idName); ?>  </option>
       <?php
            $this->_Value=trim($this->_Value);
            if(count($this->_options)>0)
            {
                foreach ($this->_options as $optionData)
                {
                    $sel="";
                    if($optionData['pid']==$this->_Value)
                    {
                        $sel=" selected ";
                    }
                    ?>
                        <option value="<?php echo $optionData['pid']; ?>" <?php echo $sel; ?> >  <?php echo $optionData['pds']; ?>  </option>
                    <?php
                }
            }
        ?>
    </select>
            
    <?php
    if($this->_onchange)
            {
            ?>
            <script>
                <?php echo $this->_onchange; ?>
            </script>

            <?php
            }
    }
}
?>