<div class="row">
  <section class="container" id="container-block"> 
    <!-- main category bloak --> 
 
    <section class="row"> 
      <!-- search and add to cart -->
      <div class="clearfix"></div>
      <!-- Page navogation part -->
      <div class="page-navigation">
        <ul class="breadcrumbs">
          <li> <a href="javascript:void(0)">Home</a> </li>
          <li> <a href="javascript:void(0)">Grocery Shop</a> </li>
          <li> <a href="javascript:void(0)">Vender List</a> </li>
        </ul>
      </div>
    </section>
    
      <div class="row cartlist">
    <div class="container">
      <div id="product-info-table">           
      <div class="col-md-9 col-lg-9 col-sm-7">
      <div class="chat_title">
      <h4><i class="fa fa-shopping-cart" aria-hidden="true"></i> Shopping Cart</h4>
      </div>
        <table class=" table-bordered  table-condensed table_checkout">
          <thead class="checkout_head">
            <tr class="tble_product">
              <th>Product image</th>
              <th>Product Name</th>
              <th>Unit price</th>
              <th>Quality</th>
              <th>Sub Total</th>
              <th style="width:10%" class="delete">&nbsp;</th>
            </tr>
          </thead>
          <tbody class="checkout-body">
            <tr class="width_prdct">
              <td data-title="Product image" class="img_width" style="width: 25%;"><img src="images/items/Carrot.png" class="img-responsive"></td>
              <td data-title="Product Name">Carrot</td>
              <td data-title="Unit price">20</td>
              <td data-title="Quantity" class="numeric"><form id='form_quanity' method='POST' action='#'>
                  <input type='button' value='-' class='qtyminus' field='quantity' />
                  <input type='text' name='quantity' value='0' class='qty' />
                  <input type='button' value='+' class='qtyplus' field='quantity' />
                </form></td>
              <td data-title="Subtotal" class="numeric">RS40</td>
              <td data-title="remove" class="remove"><i class="fa fa-trash" aria-hidden="true"></i></td>
            </tr>
            <tr class="width_prdct">
              <td data-title="Product image" class="img_width" style="width: 25%;"><img src="images/items/Cabbage.png" class="img-responsive"></td>
              <td data-title="Product Name" style="width: 25%;">Cabbage</td>
              <td data-title="Unit price">20</td>
              <td data-title="Quantity" class="numeric"><form id='form_quanity' method='POST' action='#'>
                  <input type='button' value='-' class='qtyminus' field='quantity' />
                  <input type='text' name='quantity' value='0' class='qty' />
                  <input type='button' value='+' class='qtyplus' field='quantity' />
                </form></td>
              <td data-title="Subtotal" class="numeric">RS40</td>
              <td data-title="remove" class="remove"><i class="fa fa-trash" aria-hidden="true"></i></td>
            </tr>
            <tr class="width_prdct">
              <td data-title="Product image" class="img_width" style="width: 25%;"><img src="images/items/cauliflower.png" class="img-responsive"></td>
              <td data-title="Product Name" style="width: 25%;">Califlower</td>
              <td data-title="Unit price">20</td>
              <td data-title="Quantity" class="numeric"><form id='form_quanity' method='POST' action='#'>
                  <input type='button' value='-' class='qtyminus' field='quantity' />
                  <input type='text' name='quantity' value='0' class='qty' />
                  <input type='button' value='+' class='qtyplus' field='quantity' />
                </form></td>
              <td data-title="Subtotal" class="numeric">RS40</td>
              <td data-title="remove" class="remove"><i class="fa fa-trash" aria-hidden="true"></i></td>
            </tr>
            <tr class="width_prdct">
              <td data-title="Product image" class="img_width" style="width: 25%;"><img src="images/items/Pineapple.png" class="img-responsive"></td>
              <td data-title="Product Name" style="width: 25%;">Pine apple</td>
              <td data-title="Unit price">20</td>
              <td data-title="Quantity" class="numeric"><form id='form_quanity' method='POST' action='#'>
                  <input type='button' value='-' class='qtyminus' field='quantity' />
                  <input type='text' name='quantity' value='0' class='qty' />
                  <input type='button' value='+' class='qtyplus' field='quantity' />
                </form></td>
              <td data-title="Subtotal" class="numeric">RS40</td>
              <td data-title="remove" class="remove"><i class="fa fa-trash" aria-hidden="true"></i></td>
            </tr>
            <tr class="width_prdct">
              <td data-title="Product image" class="img_width" style="width: 25%;"><img src="images/items/banana.png" class="img-responsive"></td>
              <td data-title="Product Name" style="width: 25%;">bananas</td>
              <td data-title="Unit price">20</td>
              <td data-title="Quantity" class="numeric"><form id='form_quanity' method='POST' action='#'>
                  <input type='button' value='-' class='qtyminus' field='quantity' />
                  <input type='text' name='quantity' value='0' class='qty' />
                  <input type='button' value='+' class='qtyplus' field='quantity' />
                </form></td>
              <td data-title="Subtotal" class="numeric">RS40</td>
              <td data-title="remove" class="remove"><i class="fa fa-trash" aria-hidden="true"></i></td>
            </tr>
            <tr class="width_prdct">
              <td data-title="Product image" class="img_width" style="width: 25%;"><img src="images/items/Brinjal-Long.png" class="img-responsive"></td>
              <td data-title="Product Name" style="width: 25%;">brinjal</td>
              <td data-title="Unit price">20</td>
              <td data-title="Quantity" class="numeric"><form id='form_quanity' method='POST' action='#'>
                  <input type='button' value='-' class='qtyminus' field='quantity' />
                  <input type='text' name='quantity' value='0' class='qty' />
                  <input type='button' value='+' class='qtyplus' field='quantity' />
                </form></td>
              <td data-title="Subtotal" class="numeric">RS40</td>
              <td data-title="remove" class="remove"><i class="fa fa-trash" aria-hidden="true"></i></td>
            </tr>
          </tbody>
        </table>
        
        <div class="cart_footer">
        <a href="" class="pull-left"><i class="fa fa-arrow-left" aria-hidden="true"></i> continue shopping</a>
        <a href="" class="pull-right" ><i class="fa fa-refresh" aria-hidden="true"></i>Update Cart </a>
        </div>
        
        
        
      </div>
      <div class="col-md-3 col-lg-3 col-sm-5" id="final_cost">
      <div class="pro_check">
      <a href="">Proceed to checkout <i class="fa fa-arrow-right" aria-hidden="true"></i></a>
      </div>
        <table id="check-out_side" class="std table">
          <tbody>
            <tr>
              <td>Total Amount</td>
              <td class="price">$216.51</td>
            </tr>
            <tr style="">
              <td>Shipping</td>
              <td class="price">Free shipping!</td>
            </tr>
            <tr>
              <td>Delivery charges</td>
              <td class="price">$216.51</td>
            </tr>
            <tr>
              <td>Total tax</td>
              <td class="price">$0.00</td>
            </tr>
            <tr>
              <td> Total</td>
              <td class="price">$216.51</td>
            </tr>
            <tr>
              <td colspan="2"><div class="input-append">
                  <input class="col-lg-8" id="appendedInputButton" type="text" placeholder="Coupon code">
                  <button class="col-lg-4 btn btn-success Coupon-code-btn" type="button">Apply!</button>
                </div></td>
            </tr>
          </tbody>
          <tbody>
          </tbody>
        </table>
        <a href="checkout1.html"  class="btn btn-success checkout">Check Out</a>
      </div>
    </div>
  </div>
  </div>  
        
  </section>
</div>
