<?php $wp = $this->_websiteSettings; ?>
<!-- Customer Profile -->
<div class="row">
    <section class="row" id="container-block">
        <section class="row">       
            <!-- Page navogation part -->
            <div class="container">
                <div class="page-navigation">
                    <ul class="breadcrumbs">
                        <li> <a href="javascript:void(0)">Home</a> </li>
                        <li> <a href="javascript:void(0)">Account</a> </li>
                        <li> <a href="javascript:void(0)">User Profile</a> </li>
                    </ul>
                </div>
            </div>
        </section>
        <section class="row account-info">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 col-md-12">
                        <div class="col-sm-9">
                            <div class="view-header">
                                <div class="row">
                                    <div class="pull-left">
                                <p>#123456789-Pending</p>
                            </div>
                                    <div class="pull-right">
                                        <button type="button" class="btn btn-warning">Order Picked</button>
                                        <button type="button" class="btn btn-success">Delivered</button>
                                    </div>
                            </div>
                                
                            </div>
                            <div class="view-page">
                              <!--customer details-->
                            <div class="row">
                                <div class="customer-details-view">
                                    <h3 class="heading-view-page">Customer Details</h3>
             <div class="form-group">
  
    <label>Name : Divyavani </label>
 </div>
      <div class="form-group">
    <label>Address : H-no:1-109,Filmnagar,Hyderabad </label>
    </div>
     <div class="form-group">
    <label>Phone number : 9020152496 </label>
    </div>
    <div class="form-group">
        <label class="payment_mode">Payment Type : <a href="">Cash on delivery</a>
        <a href="">Payment</a></label>
    </div>
              
                                </div>
                            </div>
      <!--vendor details--> 
      <div class="vendor-list">
       <div class="row">
                                <div class="customer-details-view">
                                    <h3 class="heading-view-page">Vendor Details</h3>
             <div class="form-group">
  
    <label>Name : Divyavani </label>
 </div>
      <div class="form-group">
    <label>Address : H-no:1-109,Filmnagar,Hyderabad </label>
    </div>
     <div class="form-group">
    <label>Phone number : 9020152496 </label>
    </div>
   
              
                                </div>
                            </div>
      
      
      
          <h3 class="heading-view-page">Product List</h3>
          <div class="row account-order" id="vendors">
             
               <div class="table-responsive border">
                            <table class="table table-bordered">
                                <thead><tr>
                                    <th class="col-xs-2">Product Image</th>
                                    <th class="col-xs-3">Product Name</th>
                                   
                                    <th class="col-xs-2">Quantity</th>
                                    <th class="col-xs-2">Total Price</th>
                                   
                                   
                                </tr>
				</thead>
                                <tbody>
                                <tr>
                                    <td></td>
                                    <td><a href="">Carrot</a></td>
                                    <td>3 kgs</td>
                                     <td>$265</td>
                                    
                                </tr>
                                 <tr>
                                    <td></td>
                                    <td><a href="">Beatroot</a></td>
                                    <td>2 kgs</td>
                                     <td>$265</td>
                                    
                                </tr>
                                 <tr>
                                    <td></td>
                                    <td><a href="">Mangoes</a></td>
                                    <td>5 kgs</td>
                                     <td>$265</td>
                                    
                                </tr>
                                 <tr>
                                    <td></td>
                                    <td><a href="">Apples</a></td>
                                    <td>3 kgs</td>
                                     <td>$265</td>
                                    
                                </tr>
                                <tr>
                                    <td></td>
                                    <td><a href="">Grapes</a></td>
                                    <td>8 kgs</td>
                                     <td>$265</td>
                                    
                                </tr>
                            </tbody></table>
                        </div>           
			</div>
             
      
      <div class="row">
          <div class="col-sm-offset-10 col-sm-2">
              <button type="button" class="btn btn-danger">Remark</button>
    
    </div>
      </div>
          </div>
      <!--vendor details--> 
      <div class="vendor-list">
       <div class="row">
                                <div class="customer-details-view">
                                    <h3 class="heading-view-page">Vendor Details</h3>
             <div class="form-group">
  
    <label>Name : Divyavani </label>
 </div>
      <div class="form-group">
    <label>Address : H-no:1-109,Filmnagar,Hyderabad </label>
    </div>
     <div class="form-group">
    <label>Phone number : 9020152496 </label>
    </div>
   
              
                                </div>
                            </div>
      
      
      
          <h3 class="heading-view-page">Product List</h3>
          <div class="row account-order" id="vendors">
             
               <div class="table-responsive border">
                            <table class="table table-bordered">
                                <thead><tr>
                                    <th class="col-xs-2">Product Image</th>
                                    <th class="col-xs-3">Product Name</th>
                                   
                                    <th class="col-xs-2">Quantity</th>
                                    <th class="col-xs-2">Total Price</th>
                                   
                                   
                                </tr>
				</thead>
                                <tbody>
                                <tr>
                                    <td></td>
                                    <td><a href="">Carrot</a></td>
                                    <td>3 kgs</td>
                                     <td>$265</td>
                                    
                                </tr>
                                 <tr>
                                    <td></td>
                                    <td><a href="">Beatroot</a></td>
                                    <td>2 kgs</td>
                                     <td>$265</td>
                                    
                                </tr>
                                 <tr>
                                    <td></td>
                                    <td><a href="">Mangoes</a></td>
                                    <td>5 kgs</td>
                                     <td>$265</td>
                                    
                                </tr>
                                 <tr>
                                    <td></td>
                                    <td><a href="">Apples</a></td>
                                    <td>3 kgs</td>
                                     <td>$265</td>
                                    
                                </tr>
                                <tr>
                                    <td></td>
                                    <td><a href="">Grapes</a></td>
                                    <td>8 kgs</td>
                                     <td>$265</td>
                                    
                                </tr>
                            </tbody></table>
                        </div>           
			</div>
             
      
      <div class="row">
          <div class="col-sm-offset-10 col-sm-2">
              <button type="button" class="btn btn-danger">Remark</button>
    
    </div>
      </div>
          </div>
     
    </div>
                    </div>
                </div>
               
        </section>
    </section>
</div>
<!-- End contant part --> 