<!-- Start contant part --> 
<div class="row">
  <section class="row" id="container-block">
    <section class="row">       
      <!-- Page navogation part -->
		  <div class="container">
			  <div class="page-navigation">
				<ul class="breadcrumbs">
				  <li> <a href="javascript:void(0)">Home</a> </li>
				  <li> <a href="javascript:void(0)">Account</a> </li>
				  <li> <a href="javascript:void(0)">Delivery Details</a> </li>
				</ul>
			  </div>
		 </div>
    </section>
    <section class="row account-info">
    <div class="container">
    <div class="row">
      <div class="col-lg-12 col-md-12">
        <?php $this->loadChildBlock("usermenu");?>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12">
        <div class="row innerWrapper account-order">
              <h1 class="block-title">My Orders</h1>
               <div class="table-responsive border">
                            <table class="table table-bordered">
                                <thead><tr>
                                    <th class="col-xs-2">Order ID</th>
                                    <th class="col-xs-3">Date</th>
                                    <th class="col-md-1 hidden-xs hidden-sm">Items</th>
                                    <th class="col-xs-2">Total Price</th>
                                    <th class="col-xs-3">Status</th>
                                    <th class="col-xs-1"></th>
                                </tr>
								</thead>
                                <tbody>
                                <tr>
                                    <td><a href="">#124321</a></td>
                                    <td>12th July 2015</td>
                                    <td class="hidden-xs hidden-sm">3</td>
                                    <td>$265</td>
                                    <td><span class="label label-info">Order Dispatched</span></td>
                                    <td><a href="deliveryview" class="btn btn-primary btn-sm btn-view">View</a></td>
                                </tr>
                                <tr>
                                    <td><a href="">#124321</a></td>
                                    <td>12th July 2015</td>
                                    <td class="hidden-xs hidden-sm">3</td>
                                    <td>$265</td>
                                    <td><span class="label label-warning">Order Pending</span></td>
                                    <td><a href="deliveryview" class="btn btn-primary btn-sm btn-view">View</a></td>
                                </tr>
                                <tr>
                                    <td><a href="">#124321</a></td>
                                    <td>12th July 2015</td>
                                    <td class="hidden-xs hidden-sm">3</td>
                                    <td>$265</td>
                                    <td><span class="label label-info">Order Onway</span></td>
                                    <td><a href="deliveryview" class="btn btn-primary btn-sm btn-view">View</a></td>
                                </tr>
                                <tr>
                                    <td><a href="">#124321</a></td>
                                    <td>12th July 2015</td>
                                    <td class="hidden-xs hidden-sm">3</td>
                                    <td>$265</td>
                                    <td><span class="label label-success">Completed</span></td>
                                    <td><a href="deliveryview" class="btn btn-primary btn-sm btn-view">View</a></td>
                                </tr>
                                <tr>
                                    <td><a href="">#124321</a></td>
                                    <td>12th July 2015</td>
                                    <td class="hidden-xs hidden-sm">3</td>
                                    <td>$265</td>
                                    <td><span class="label label-danger">Canceled</span></td>
                                    <td><a href="deliveryview" class="btn btn-primary btn-sm btn-view">View</a></td>
                                </tr>
                            </tbody></table>
                        </div>           
			</div>
        </div>
        <!--/row end--> 
        
      </div>
    </div>
	</section>
  </section>
</div>
<!-- End contant part --> 