<?php $wp = $this->_websiteSettings; ?>
<!-- Customer Profile -->
<div class="row">
    <section class="row" id="container-block">
        <section class="row">       
            <!-- Page navogation part -->
            <div class="container">
                <div class="page-navigation">
                    <ul class="breadcrumbs">
                        <li> <a href="javascript:void(0)">Home</a> </li>
                        <li> <a href="javascript:void(0)">Order</a> </li>
                        <li> <a href="javascript:void(0)">Invoice</a> </li>
                    </ul>
                </div>
            </div>
        </section>
        <section class="row">
            <div class="container">                
                <div class="row invoice_data">
                    <h1>Invoice Id : #ZE0000264</h1>
                    <h3>Order Id : #ORD0002564</h3>

                    <div class="ord_billing">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="row">
                                    <h3>Billing Address</h3>
                                    <ul>
                                        <li>Siva Kumar</li>
                                        <li>3-6-190/1 , Hyderguda</li>
                                        <li>Himayat Nagar, Hyderabad</li>
                                        <li>Telanagana</li>
                                        <li>Country - 500029</li>
                                        <li>Phone : 9030745148</li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="row">
                                    <h3>Shipping Address</h3>
                                    <ul>
                                        <li>Siva Kumar</li>
                                        <li>3-6-190/1 , Hyderguda</li>
                                        <li>Himayat Nagar, Hyderabad</li>
                                        <li>Telanagana</li>
                                        <li>Country - 500029</li>
                                        <li>Phone : 9030745148</li>
                                    </ul>
                                </div>
                            </div>
                        </div>                        
                    </div>
                    <div class="paymant_info">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="row">
                                    <h3>Payment Information</h3>
                                    <p>Cash On Delivary</p>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="row">
                                    <h3>Shipping Information</h3>
                                    <p>Flat Courior</p>
                                </div>
                            </div>
                        </div>                        
                    </div>
                    <div class="row product_info">
                        <div class="col-md-12 no-padding">
                            <div class="row">
                                <table class="table table-bordered table-responsive">
                                    <thead>
                                        <tr>
                                            <th>Product Name</th>
                                            <th>Unit Price</th>                                            
                                            <th>Quality</th>
                                            <th>Price</th>
                                            <th>Discount</th>
                                            <th>Sub Total</th>
                                        </tr>
                                    </thead>     
                                    <tbody> 
                                        <tr> 
                                            <td>Carrot ( 2Kg )</td>
                                            <td>25</td> 
                                            <td>2</td> 
                                            <td>50.00</td> 
                                            <td>0.00</td> 
                                            <td>50.00</td> 
                                        </tr> 
                                        <tr> 
                                            <td>Brinjal ( 2Kg )</td>
                                            <td>25</td> 
                                            <td>2</td> 
                                            <td>50.00</td> 
                                            <td>0.00</td> 
                                            <td>50.00</td> 
                                        </tr> 
                                        <tr> 
                                            <td>Pine Apple( 2Kg )</td>
                                            <td>25</td> 
                                            <td>2</td> 
                                            <td>50.00</td> 
                                            <td>0.00</td> 
                                            <td>50.00</td> 
                                        </tr> 
                                        <tr> 
                                            <td>Potato( 2Kg )</td>
                                            <td>25</td> 
                                            <td>2</td> 
                                            <td>50.00</td> 
                                            <td>0.00</td> 
                                            <td>50.00</td> 
                                        </tr> 
                                        <tr> 
                                            <td>Califlower( 2Kg )</td>
                                            <td>25</td> 
                                            <td>2</td> 
                                            <td>50.00</td> 
                                            <td>0.00</td> 
                                            <td>50.00</td>
                                        </tr> 
                                    </tbody> 

                                </table>
                            </div>                                
                        </div>                        
                    </div>
                    <div class="row inc_total">
                        <div class="col-md-5 col-md-offset-7">
                            <div class="row">
                                <ul>
                                    <li> <div class="col-xs-6">Subtotal</div><div class="col-xs-1"> :</div><div class="col-xs-5">Rs 500</div></li>
                                    <li> <div class="col-xs-6">Tax</div><div class="col-xs-1"> :</div><div class="col-xs-5">Rs 50</div></li>
                                    <li> <div class="col-xs-6">shipping / handling</div><div class="col-xs-1"> :</div><div class="col-xs-5">Rs 50</div></li>
                                    <li> <div class="col-xs-6">Grand Total</div><div class="col-xs-1"> :</div><div class="col-xs-5">Rs 600</div></li>                        
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </section>
</div>
<!-- End contant part --> 
<script>
    require([
        'css!../css/Ordermanagement/invoice',
    ], function () {
    });
</script>