<div class="row">
    <div class="col-md-12"> 
        <div class="row vendor_according">    
            <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                <div class="panel panel-default">
                    <div class="panel-heading" role="tab" id="headingOne">
                        <h4 class="panel-title">
                            Order List                                 
                            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#pending_orders" aria-expanded="true" aria-controls="collapseOne">
                           <span class="glyphicon glyphicon-plus pull-right" aria-hidden="true"></span> </a>
                        </h4>
                    </div>
                    <div id="pending_orders" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                        <div class="panel-body">
                            <div id="order-tables-order">
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th class="numeric">Order No.</th>
                                            <th class="numeric">Date</th>
                                            <th class="numeric">Payment Mode</th>
                                            <th class="numeric">Total Amount</th>
                                            <th class="numeric">Dispatched</th>

                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td data-title="Order No.">1001</td>
                                            <td data-title="Date">16/04/2107</td>
                                            <td data-title="Payment Mode" class="numeric">-----</td>
                                            <td data-title="Total Amount" class="numeric">Rs.10,000</td>
                                            <td data-title="Dispatched" class="numeric">----</td>

                                        </tr>
                                        <tr>
                                            <td data-title="Order No.">1002</td>
                                            <td data-title="Date">12/12/2107</td>
                                            <td data-title="Payment Mode" class="numeric">-----</td>
                                            <td data-title="Total Amount" class="numeric">Rs.10,000</td>
                                            <td data-title="Dispatched" class="numeric">----</td>

                                        </tr>
                                        <tr>
                                            <td data-title="Order No.">1003</td>
                                            <td data-title="Date">15/05/2107</td>
                                            <td data-title="Payment Mode" class="numeric">-----</td>
                                            <td data-title="Total Amount" class="numeric">Rs.10,000</td>
                                            <td data-title="Dispatched" class="numeric">----</td>

                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>    

