<div class="row">
    <div class="col-sm-5 left-padding">
        <div id="gallery1" class="photo-gallery">
            <div class="current-photo"> <img> </div>
            <div class="photo-list">
                <ul>
                    <li data-src="https://unsplash.it/600/400?image=271">
                        <div class="thumbnail"> <img src="https://unsplash.it/600/400?image=271" title="" alt="" /> </div>
                    </li>
                    <li data-src="https://unsplash.it/600/400?image=382">
                        <div class="thumbnail"> <img src="https://unsplash.it/600/400?image=382" title="" alt="" /> </div>
                    </li>
                    <li data-src="https://unsplash.it/600/400?image=373">
                        <div class="thumbnail"> <img src="https://unsplash.it/600/400?image=373" title="" alt="" /> </div>
                    </li>
                    <li data-src="https://unsplash.it/600/400?image=380">
                        <div class="thumbnail"> <img src="https://unsplash.it/600/400?image=380" title="" alt="" /> </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-sm-7 right-padding">
        <div class="product-view">
            <h2>Carrot Product</h2>
            <p><span id="stars-existing" class="starrr" data-rating='4'></span><span class="product-review">(0) Review</span></p>
            <p class="product-short-description ">The carrot (Daucus carota L.) belongs to the family Apiaceae. It is related to celery, celeriac,
                coriander, fennel, parsnip and parsley, which are all members of this family. The carrot
                originated in Asia. Initially the roots were long and thin, and either purple or yellow in colour.
                These colours, as well as white and orange, still exist, with the orange or orange-red colours
                being by far the most popular today. </p>
        </div>
        <div class="view-product-info">
            <div class="product-price-block">
                <div class="product-qnty-list">
                    <select class="" id="">
                        <option value="">3kg - 250Rs</option>
                        <option value="">2kg - 190Rs</option>
                        <option value="">1kg - 100Rs</option>
                        <option value="">500g - 60Rs</option>
                        <option value="">250g - 35Rs</option>
                    </select>
                </div>
                <div class="product-offer"><span>-30%</span></div>
                <div class="view-product-price"> <span class="pr-total-price"><i class="fa fa-inr" aria-hidden="true"></i>500.00</span> <span class="pr-price"><i class="fa fa-inr" aria-hidden="true">450.00</i></span> </div>
            </div>
            <div class="product-stock-info">Availability: In stock</div>
            <div class="product-add-to-cart">
                <div class="product-qtr">
                    <input type="text" name="pr_qty" id="pr_qty" value="1" maxlength="12" />
                    <div class="pr-qtr-handler"> <a href="javascript:void(0)" class="pr_qty_inc"><i class="fa fa-plus" aria-hidden="true"></i></a> <a href="javascript:void(0)" class="pr_qty_dec"><i class="fa fa-window-minimize" aria-hidden="true"></i></a> </div>
                </div>
                <div class="add-to-product">
                    <button type="button" id="" name=""><i class="fa fa-shopping-cart" aria-hidden="true"></i>Add To Cart</button>
                </div>
                <div class="add-to-wish">
                    <button type="button" id="" name=""><i class="fa fa-heart" aria-hidden="true"></i></button>
                </div>
            </div>
        </div>
    </div>
</div>
