<?php
$controllerObj = $this->_controllerObj;
//echo "<pre>"; print_r($controllerObj); die;
$performAction = $controllerObj->checkActionPerform();
$performMraAction = $controllerObj->checkMraActionPerform();
$performMultiEditAction = $controllerObj->checkMultiEditActionInProgress();
$multiEditFields = $controllerObj->getMultiEditAttributes();
if ($controllerObj->_totalRecordsCount < 1) {
    $controllerObj->_totalRecordsCount = 1;
}
?>
<div id="total_<?php echo $controllerObj->_nodeName; ?>" name="total_<?php echo $controllerObj->_nodeName; ?>">
    <?php
    if (!$performMultiEditAction) {
        ?>
        <div>
            <?php
            $parentPath = "";
            if ($controllerObj->_parentNode) {
                $parentPath.=$controllerObj->_parentNode . "/";
                $parentPath.=$controllerObj->_parentAction . "/";
                $parentPath.=$controllerObj->_parentSelector;
            }
            if (count($controllerObj->_singleActions) && $performAction == 1) {
                foreach ($controllerObj->_singleActions as $actionName) {
                    ?>
                    <span style="padding-left: 25px;">
                        <a href="<?php echo $controllerObj->_websiteHostUrl . $actionName["code"] . "/0/" . $parentPath; ?>">
                            <button class="btn btn-warning"><?php echo $actionName['name']; ?></button>
                        </a>
                    </span>
                    <?php
                }
            }
            ?>
        </div>
        <?php
    }
    ?>
    <div class="box box-primary">

        <div class="box-header with-border">
            <h3 class="box-title"><?php echo $controllerObj->getLabel($controllerObj->_currentAction); ?></h3>
            <div class="box-tools pull-right">
                <button class="btn btn-box-tool" data-widget="collapse"><i class="icon-chevron-down"></i></button>
            </div>
        </div>

        <div class=" box-body chart-responsive" style="margin-top:15px; overflow-x:auto; overflow-y:hidden;">
            <div>
                <div class="dataTables_filter" id="sample_1_filter">
                    <label></label>
                </div>
            </div>
            <div id="sample-table-2_wrapper" class="dataTables_wrapper" role="grid">
                <form id="result_<?php echo $controllerObj->_nodeName; ?>" name="result_<?php echo $controllerObj->_nodeName; ?>" >
                    <div id="result_<?php echo $controllerObj->_nodeName; ?>_div" name="result_<?php echo $controllerObj->_nodeName; ?>_div">
                        <?php
                        if (!$performMultiEditAction) {
                            ?>
                            <div style=" padding-left: 18px;">
                                <span style=" padding-left: 18px;">RPP:</span>
                                <span style=" padding-left: 18px;">
                                    <select size="1" name="rpp" aria-controls="rpp" class="input-mini" onchange="setrpp('<?php echo $controllerObj->_nodeName; ?>', this.value);
                                            samplefun('<?php echo $controllerObj->_nodeName; ?>');">
                                                <?php
                                                $in = "1";
                                                while ($controllerObj->_wsrpp * ($in - 1) < $controllerObj->_totalRecordsCount) {
                                                    if ($controllerObj->_wsrpp * $in == $controllerObj->_rpp) {
                                                        $sel = " selected ";
                                                    } else {
                                                        $sel = "";
                                                    }
                                                    echo $output = '<option value="' . ($controllerObj->_wsrpp * $in) . '" ' . $sel . '>' . ($controllerObj->_wsrpp * $in) . '</option>';
                                                    $in++;
                                                }
                                                ?>
                                    </select>
                                </span>
                                <span style=" padding-left: 18px;">Page:</span>
                                <span style=" padding-left: 18px;">

                                    <select size="1" name="page" aria-controls="page" class="input-mini" onchange="setpage('<?php echo $controllerObj->_nodeName; ?>', this.value);
                                            samplefun('<?php echo $controllerObj->_nodeName; ?>');">
                                                <?php
                                                $in = "1";
                                                while ($controllerObj->_rpp * ($in - 1) <= $controllerObj->_totalRecordsCount) {
                                                    if ($in == $controllerObj->_page) {
                                                        $sel = " selected ";
                                                    } else {
                                                        $sel = "";
                                                    }
                                                    echo '<option value="' . $in . '" ' . $sel . '>' . $in . '</option>';
                                                    $in++;
                                                }
                                                ?>
                                    </select>
                                </span>
                                <span style=" padding-left: 18px;">Display Records: <?php echo $controllerObj->_rpp * ($controllerObj->_page - 1); ?> to <?php echo $controllerObj->_rpp * ($controllerObj->_page) > $controllerObj->_totalRecordsCount ? $controllerObj->_totalRecordsCount : $controllerObj->_rpp * ($controllerObj->_page); ?>  of <?php echo $controllerObj->_totalRecordsCount; ?></span>
                                </span>
                            </div>                    
                            <?php
                        }
                        if ($controllerObj->checkMultiEditAction()) {
                            ?>
                            <div>
                                <span>
                                    <?php
                                    if ($performMultiEditAction) {
                                        ?>
                                        <div id="<?php echo $controllerObj->_nodeName; ?>_error_div" name="<?php echo $controllerObj->_nodeName; ?>_error_div"></div>
                                        <input type="button" id="multieditbutton" name="multieditbutton" value="Cancel" class="btn btn-danger" onclick="updateresultdiv('cancel', '<?php echo $controllerObj->_nodeName; ?>')">
                                        <?php
                                    } else {
                                        ?>      

                                        <input type="button" id="multieditbutton" name="multieditbutton" value="Multiedit" class="btn btn-danger" onclick="updateresultdiv('edit', '<?php echo $controllerObj->_nodeName; ?>')">
                                        <?php
                                    }
                                    ?>
                                </span>
                            </div>
                            <?php
                        }
                        ?>

                        <div style="text-align: center;margin-top: 13px;">                                            
                            <table id="sample-table-2" class="table table-striped table-bordered table-hover dataTable">
                                <thead>
                                    <tr role="row">
                                        <?php
                                        $style = "";
                                        if ($performMultiEditAction) {
                                            $style = 'style="display:none;"';
                                        }
                                        ?>
                                        <th class="actionselection" >
                                            <?php
                                            if ($performAction == 1 && $performMraAction == 1) {
                                                ?>
                                                <input <?php echo $style; ?> type="checkbox" id="checkall" value="1" onclick="checkaction('mra_<?php echo $controllerObj->_nodeName; ?>', this.checked, 'class');"/> 
                                                <?php
                                            }
                                            ?>
                                        </th>
                                        <th>Action</th>
                                        <?php
                                        if (count($controllerObj->_showAttributes) > 0) {
                                            foreach ($controllerObj->_showAttributes as $FieldName) {
                                                ?>
                                                <th><?php echo $controllerObj->getLabel($FieldName); ?></th>
                                                <?php
                                            }
                                        }
                                        ?>
                                    </tr>
                                    <?php
                                    $style = "";
                                    if ($performMultiEditAction) {
                                        $style = 'style="display:none;"';
                                    }
                                    ?>
                                    <tr role="row" <?php echo $style; ?>>
                                        <th class="actionselection" ></th>
                                        <th>
                                            <input type="hidden" id="action_id" name="action_id" value="admin">
                                            <input type="button" id="buttonsearch" name="buttonsearch" value="Search" onclick="setpagezero();
                                                    samplefun('<?php echo $controllerObj->_nodeName; ?>');" class="btn bsetpagezerotn-info" style="border-radius: 15px;" />	   
                                            <input type="hidden" id="<?php echo $controllerObj->_nodeName; ?>_module" name="<?php echo $controllerObj->_nodeName; ?>_module" value="codebasedsettings">
                                            <input type="hidden" id="<?php echo $controllerObj->_nodeName; ?>_node" name="<?php echo $controllerObj->_nodeName; ?>_node" value="<?php echo $controllerObj->_nodeName; ?>">
                                            <input type="hidden" id="rpp_<?php echo $controllerObj->_nodeName; ?>" name="rpp_<?php echo $controllerObj->_nodeName; ?>" value="<?php echo $controllerObj->_rpp; ?>">
                                            <input type="hidden" id="page_<?php echo $controllerObj->_nodeName; ?>" name="page_<?php echo $controllerObj->_nodeName; ?>" value="<?php echo $controllerObj->_page; ?>">			    
                                            <input type="hidden" id="<?php echo $controllerObj->_nodeName; ?>_parentaction" name="<?php echo $controllerObj->_nodeName; ?>_parentaction" value="<?php echo $controllerObj->_parentAction; ?>">
                                            <input type="hidden" id="<?php echo $controllerObj->_nodeName; ?>_parentnode" name="<?php echo $controllerObj->_nodeName; ?>_parentnode" value="<?php echo $controllerObj->_parentNode; ?>">
                                            <input type="hidden" id="<?php echo $controllerObj->_nodeName; ?>_parentidvalue" name="<?php echo $controllerObj->_nodeName; ?>_parentidvalue" value="<?php echo $controllerObj->_parentSelector; ?>">
                                            <input type="hidden" id="<?php echo $controllerObj->_nodeName; ?>_multiedit" name="<?php echo $controllerObj->_nodeName; ?>_multiedit" value="0">

                                        </th>                                                                                
                                        <?php
                                        if (count($controllerObj->_showAttributes) > 0) {
                                            foreach ($controllerObj->_showAttributes as $FieldName) {
                                                ?>

                                                <th>
                                                    <?php
                                                    if (in_array($FieldName, $controllerObj->_searchAttributes)) {
                                                        ?>
                                            <div id="value_<?php echo $FieldName; ?>" name="value_<?php echo $FieldName; ?>">

                                                <span id="admin_<?php echo $FieldName; ?>" name="admin_<?php echo $FieldName; ?>">
                                                    <?php
                                                    if (Core::inArray($FieldName, $controllerObj->_boolAttributes)) {
                                                        ?>
                                                        <select class="input-small m-wrap" name="<?php echo $FieldName; ?>" id="<?php echo $FieldName; ?>">
                                                            <option value=""> ALL </option>
                                                            <?php
                                                            $sel = "";
                                                            if (Core::getValueFromArray($controllerObj->_requestedData, $FieldName) == 1) {
                                                                $sel = " selected ";
                                                            }
                                                            ?>
                                                            <option <?php echo $sel; ?> value="1"> YES </option>
                                                            <?php
                                                            $sel = "";
                                                            if (Core::getValueFromArray($controllerObj->_requestedData, $FieldName) == "0") {
                                                                $sel = " selected ";
                                                            }
                                                            ?>
                                                            <option <?php echo $sel; ?> value="0"> NO </option>
                                                        </select>
                                                        <?php
                                                    } else {
                                                        ?>

                                                        <input type="text" class="input-small" name="<?php echo $FieldName; ?>" id="<?php echo $FieldName; ?>" value="<?php echo \Core::getValueFromArray($controllerObj->_requestedData, $FieldName); ?>">
                                                        <?php
                                                    }
                                                    ?>
                                                </span>	
                                            </div>
                                            <?php
                                        }
                                        ?>
                                        </th>
                                        <?php
                                    }
                                }
                                ?> 
                                <th style="display:none">
                                    <input type="hidden" name="defaultselectnodes" id="defaultselectnodes" value="">
                                </th>
                                </tr>                            
                                </thead>
                                <tbody role="alert" aria-live="polite" aria-relevant="all">
                                    <?php
                                    if (count($controllerObj->_collections) > 0) {
                                        foreach ($controllerObj->_collections as $row) {
                                            if (key_exists($controllerObj->_primaryKey . "pk", $row)) {
                                                $primarykeyValue = $row[$controllerObj->_primaryKey . "pk"];
                                            } else {
                                                $primarykeyValue = $row[$controllerObj->_primaryKey];
                                            }
                                            ?>
                                            <tr>
                                                <td class="actionselection" >
                                                    <?php
                                                    if ($performMultiEditAction) {
                                                        echo '<input type="hidden" name="' . $controllerObj->_nodeName . "_save[" . $primarykeyValue . "][" . $controllerObj->_autoKey . "]" . '" id="' . $controllerObj->_nodeName . "_" . $primarykeyValue . '_' . $controllerObj->_autoKey . '" value="' . $row[$controllerObj->_autoKey] . '"/>';
                                                    } else {
                                                        if ($performAction == 1 && $performMraAction == 1) {
                                                            ?>
                                                            <input type="checkbox" class="mra_<?php echo $controllerObj->_nodeName; ?>" id="<?php echo $controllerObj->_nodeName . "_" . $primarykeyValue; ?>" name="mra_<?php echo $controllerObj->_nodeName; ?>[]" value="<?php echo $primarykeyValue; ?>" /> 
                                                            <?php
                                                        }
                                                    }
                                                    ?>
                                                </td>
                                                <td>
                                                    <?php
                                                    if (!$performMultiEditAction) {
                                                        ?>
                                                        <span>
                                                            <?php
                                                            if (count($controllerObj->_individualActions) > 0) {
                                                                ?>

                                                                <?php
                                                                foreach ($controllerObj->_individualActions as $actionData) {
                                                                    if ($performAction == 1 || $actionData['code'] == 'view') {
                                                                        if ($controllerObj->recordActionPerform($actionData['code'], $primarykeyValue)) {
                                                                            $controllerObj->loadActionButton($actionData, $primarykeyValue, $parentPath);
                                                                        }
                                                                    }
                                                                }
                                                                ?>

                                                            </span>
                                                            <?php
                                                        }
                                                    }
                                                    ?>
                                                </td>
                                                <?php
                                                foreach ($controllerObj->_showAttributes as $FieldName) {
                                                    ?>
                                                    <td>
                                                        <?php
                                                        $controllerObj->loadAttribute($FieldName, $row);
                                                        ?>
                                                        <div class="error_message" id="error_<?php echo $controllerObj->_nodeName . "_" . $primarykeyValue . "_" . $FieldName; ?>"></div>

                                                    </td>
                                                    <?php
                                                }
                                                ?>

                                            </tr>
                                            <?php
                                        }
                                    }
                                    ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </form>

                <?php
                if (!$performMultiEditAction) {
                    if ($performMraAction == 1 && $performAction == 1) {
                        ?>
                        <form id="mradata_<?php echo $controllerObj->_nodeName; ?>" name="mradata_<?php echo $controllerObj->_nodeName; ?>">


                            <input type="hidden" id="<?php echo $controllerObj->_nodeName; ?>_parentaction" name="<?php echo $controllerObj->_nodeName; ?>_parentaction" value="<?php echo $controllerObj->_parentAction; ?>">
                            <input type="hidden" id="<?php echo $controllerObj->_nodeName; ?>_parentnode" name="<?php echo $controllerObj->_nodeName; ?>_parentnode" value="<?php echo $controllerObj->_parentNode; ?>">
                            <input type="hidden" id="<?php echo $controllerObj->_nodeName; ?>_parentidvalue" name="<?php echo $controllerObj->_nodeName; ?>_parentidvalue" value="<?php echo $controllerObj->_parentSelector; ?>">
                            <input type="hidden" id="<?php echo $controllerObj->_nodeName; ?>_selector" name="<?php echo $controllerObj->_nodeName; ?>_selector" value="">

                            <span style="align:left">
                                <select id="<?php echo $controllerObj->_nodeName; ?>_mraAction" name="<?php echo $controllerObj->_nodeName; ?>_mraAction" class="input-medium m-wrap" onchange="getMRATemplate('<?php echo $controllerObj->_nodeName; ?>');">
                                    <option value="">Select Action</option>
                                    <?php
                                    foreach ($controllerObj->_mraActions as $actionData) {
                                        echo '<option value="mra' . $actionData['code'] . '"> ' . $actionData['name'] . '  </option>';
                                    }
                                    ?>                                	
                                </select>
                            </span>
                            <span id="mrahtml_<?php echo $controllerObj->_nodeName; ?>" name="mrahtml_<?php echo $controllerObj->_nodeName; ?>">
                            </span>
                            <span id="mraerror_<?php echo $controllerObj->_nodeName; ?>" name="mraerror_<?php echo $controllerObj->_nodeName; ?>" style="color:red;">
                            </span>


                            <div>
                                <input type="button" id="mra_submit" name="mra_submit" class="btn btn-danger" value="Go" onclick="getmraaction('<?php echo $controllerObj->_nodeName; ?>');">
                            </div>
                        </form>
                        <?php
                    }
                } else {
                    ?>
                    <div>
                        <span style="margin-top:15px;" >
                            <button id=" multieditsave" name="multieditsave" class="btn btn-danger" onclick="return multieditformsubmit('<?php echo $controllerObj->_nodeName; ?>');">Save
                        </span>
                    </div>
                    <?php
                }
                ?>                
            </div>
        </div>
    </div>	
</div>