<div id="main-content-right">
<div class="row" id="dashboard-widget">
    <div class="col-sm-3 no-padding">
        <div class="row widget-box">
            <h2>Total Products</h2>
            <div class="row widget-box-text">
                <div class="col-sm-3 widget-text-left bg-green no-padding">
                <i class="fa fa-product-hunt" aria-hidden="true"></i>
                </div>
                <div class="col-sm-9 widget-text-right  no-padding">
                  <h1>Products</h1>
                  <h3 class="cl-green">5678</h3>
                   </div>
        </div>
    </div>
    
</div>
    

 <div class="col-sm-3 no-padding">
        <div class="row widget-box">
            <h2>Total Orders</h2>
            <div class="row widget-box-text">
                <div class="col-sm-3 widget-text-left bg-red no-padding">
                <i class="fa fa-first-order" aria-hidden="true"></i>

                </div>
                <div class="col-sm-9 widget-text-right  no-padding">
                  <h1>Orders</h1>
                  <h3 class="cl-red">5678</h3>
                   </div>
        </div>
    </div>
    
</div>
     <div class="col-sm-3 no-padding">
        <div class="row widget-box">
            <h2>Total Vendors</h2>
            <div class="row widget-box-text">
                <div class="col-sm-3 widget-text-left bg-purple no-padding">
                <i class="fa fa-users" aria-hidden="true"></i>

                </div>
                <div class="col-sm-9 widget-text-right  no-padding">
                  <h1>Vendors</h1>
                  <h3 class="cl-purple">5678</h3>
                   </div>
        </div>
    </div>
    
</div>
    <div class="col-sm-3 no-padding">
        <div class="row widget-box">
            <h2>Total Visitors</h2>
            <div class="row widget-box-text">
                <div class="col-sm-3 widget-text-left bg-blue no-padding">
                <i class="fa fa-users" aria-hidden="true"></i>

                </div>
                <div class="col-sm-9 widget-text-right  no-padding">
                  <h1>Visitors</h1>
                  <h3 class="cl-blue">5678</h3>
                   </div>
        </div>
    </div>
    
</div>
    
    </div>
<!--order list-->
<div class="row">
    <section class="pending-orders">
                <div class="row margin-0">
                    <div class="col-sm-5 no-padding">
                        <div id="left-side">
                        <div class="header">
                        <div class="pull-left">
                           <div class="checkbox">
  <label><input type="checkbox" value=""><span class="all"> All</span></label>
</div> 
</div>
<div class="pull-right" id="left-header">
<select class="selectpicker" id="select_field">
                              <option>Pending</option>
                              <option>Last 7 days</option>
                              <option>Last 30 days</option>
                              <option>All Times</option>
                            </select>
                            </div>

                        </div>
                        <div id="order-table">
                            <table class="table table-striped">
  <thead>
    
  </thead>
  <tbody>
    <tr class="table-fields">
      <td scope="">   
      <div class="checkbox">
  <label><input type="checkbox" value=""></label>
    </div> 
    </td>
      <td>#12345678
      <br>
      <span class="span1">Pending</span>
      </td>
      <td>Test name
      <br>
      <span>Divya</span>
      </td>
      <td>Rs.10,000
      <br>
      <span>20days</span>
      </td>
    </tr>
    <tr class="table-fields">
      <td scope="">   
      <div class="checkbox">
  <label><input type="checkbox" value=""></label>
    </div> 
    </td>
      <td>#12345678
      <br>
      <span class="span1">Pending</span>
      </td>
      <td>Test name
      <br>
      <span>Divya</span>
      </td>
      <td>Rs.10,000
      <br>
      <span>20days</span>
      </td>
    </tr>
    <tr class="table-fields">
      <td scope="">   
      <div class="checkbox">
  <label><input type="checkbox" value=""></label>
    </div> 
    </td>
      <td>#12345678
      <br>
      <span class="span1">Pending</span>
      </td>
      <td>Test name
      <br>
      <span>Divya</span>
      </td>
      <td>Rs.10,000
      <br>
      <span>20days</span>
      </td>
    </tr>
    <tr class="table-fields">
      <td scope="">   
      <div class="checkbox">
  <label><input type="checkbox" value=""></label>
    </div> 
    </td>
      <td>#12345678
      <br>
      <span class="span1">Pending</span>
      </td>
      <td>Test name
      <br>
      <span>Divya</span>
      </td>
      <td>Rs.10,000
      <br>
      <span>20days</span>
      </td>
    </tr>
    <tr class="table-fields">
      <td scope="">   
      <div class="checkbox">
  <label><input type="checkbox" value=""></label>
    </div> 
    </td>
      <td>#12345678
      <br>
      <span class="span1">Pending</span>
      </td>
      <td>Test name
      <br>
      <span>Divya</span>
      </td>
      <td>Rs.10,000
      <br>
      <span>20days</span>
      </td>
    </tr>
    <tr class="table-fields">
      <td scope="">   
      <div class="checkbox">
  <label><input type="checkbox" value=""></label>
    </div> 
    </td>
      <td>#12345678
      <br>
      <span class="span1">Pending</span>
      </td>
      <td>Test name
      <br>
      <span>Divya</span>
      </td>
      <td>Rs.10,000
      <br>
      <span>20days</span>
      </td>
    </tr>
  </tbody>
</table>
                        </div>
                    </div>
                    </div>
                    <div class="col-sm-7 no-padding">
                        <div id="right-side">
                        <div class="header">
                            <div class="pull-left">
                                <p>#123456789-Pending</p>
                            </div>
                            <div class="pull-right">
                                <button type="button" class="btn btn-warning">Print Invoice</button>
                                <button type="button" class="btn btn-info" data-toggle="modal" data-target="#myModal">Assign Pickup</button>
                            <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog modal-md">
      <div class="modal-content">
        <div class="modal-header header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          
              <p>#123456789</p>
         
        </div>
          <div class="modal-body" id="assign-status">
        <div class="pending-details">
           
            <div class="mark_desc">
                <h2><b>Customer Address</b></h2>
            </div>
            </div>
            <div class="pending-status">
            <h3 class="customer-details-order">Divyavani </h3>
            <h3 class="customer-details-order">Hyderabad </h3>
            <h3 class="customer-details-order">9948750841 </h3>
            <h3 class="customer-details-order">8801-56 </h3>
            </div>
         <ul id="assign-boy">
             <li>
             <div class="radio">
  <label><input type="radio" name="optradio">Ravi -<span class="assign-area">Madhapur</span> </label>
</div>
</li>
<li>
             <div class="radio">
  <label><input type="radio" name="optradio">Ravi -<span class="assign-area">Hitec City</span></label>
</div>
</li>
<li>
             <div class="radio">
  <label><input type="radio" name="optradio">Ravi -<span class="assign-area">Filmnagar</span></label>
</div>
</li>
<li>
             <div class="radio">
  <label><input type="radio" name="optradio">Ravi -<span class="assign-area">Banjarahills</span></label>
</div>
</li>
         </ul>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
  
  
                                <button type="button" class="btn btn-danger">Cancel order</button>
                            </div>
                        </div>
                        <div class="right-main">
                            
                      
                            <div class="row margin-0">
                                  <div class="table-responsive">
                                      
                           <div class="table_orders">
            <table class="table table-bordered">
                   
	 <thead>
    <tr>
      <th>Product</th>
      <th>Quality</th>
      <th>SKU</th>
      <th>Unit Price</th>
      <th>Total</th>
    </tr>
  </thead>
                        
    <tbody>
    <tr>
      <td data-title="Product">Vegetables</td>
      <td data-title="Quality">1</td>
      <td data-title="SKU">#5467</td>
      <td data-title="Unit Price">Rs.10,000</td>
       <td data-title="Total">Rs.20,000</td>
      
      
    </tr>
    <tr>
      <td data-title="Sub Total" colspan="4">
          <div class="text-right"><span class="display-none-order">Sub total</span></div></td>
      <td class="cost">Rs.10,000</td>
      
    </tr>
   <tr>
      <td data-title="Shipping Cost" colspan="4">
          <div class="text-right"><span class="display-none-order">Shipping Cost</span></div></td>
      <td class="cost">Rs.0.00</td>
      
    </tr>
      <tr>
      <td data-title="VAT / CST(5% inclusive" colspan="4">
          <div class="text-right"><span class="display-none-order">VAT / CST(5% inclusive)</span></div></td>
      <td class="cost">Rs.53.14</td>
      
    </tr>
    <tr>
      <td data-title="Total" colspan="4">
          <div class="text-right"><span class="display-none-order">Total</span></div></td>
      <td class="cost">Rs.20,000</td>
      
    </tr>
  </tbody>
			
</table>
             </div>
                                         </div>
                            </div>
                            
                            
                            

    <div class="history">
    <div class="history-details">
    <div class="row margin-0">
        <div class="pull-left">
            <p>Order History</p>
        </div>
        <div class="pull-right">
            <a href="">Add Comments</a>
        </div>
        </div>

        <div class="table-history-status">
             <div class="table_orders">
                 <table class="table table-bordered" id="bordered">
                   
	<thead>
    <tr>
      <th>Data Added</th>
      <th>Comment</th>
      <th>Status</th>
      <th>Customer Notified</th>
      
    </tr>
  </thead>
                        
    <tbody>
    <tr>
      <td data-title="Data Added">20/02/2017</td>
      <td data-title="Comment">I can tsa fdslfiu</td>
      <td data-title="Status">Pending</td>
      <td data-title="Customer Notified">YES</td>
      
    </tr>
   
  </tbody>
			
</table>
             </div>
  
  
  
        </div>

        </div>
    </div>

    <div class="row margin-0">
        
       <div class="col-sm-3 no-padding">
        <div class="pending-details">
            
            <div class="mark_desc">
                <p>Payment Details</p>
            </div>
            </div>
            <div class="pending-status">
            <p class="assign-data">Cash on delivery</p>
            </div>
        </div>
        <div class="col-sm-3 no-padding">
        <div class="pending-details">
            
            <div class="mark_desc">
                <p>Invoice No.</p>
            </div>
            </div>
            <div class="pending-status">
            <p class="assign-data"><a href="">Generate</a> </p>
            </div>
        </div>
    
    
       <div class="col-sm-3 no-padding">
        <div class="pending-details">
            
            <div class="mark_desc">
                <p>Customer Details</p>
            </div>
            </div>
            <div class="pending-status">
            <p class="customer-details-order">Divyavani </p>
            <p class="customer-details-order">Divyavani@gmail.com </p>
            <p class="customer-details-order">9701450236 </p>
            </div>
        </div> 
        <div class="col-sm-3 no-padding">
        <div class="pending-details">
           
            <div class="mark_desc">
                <p>Customer Address</p>
            </div>
            </div>
            <div class="pending-status">
            <p class="customer-details-order">Divyavani </p>
            <p class="customer-details-order">Hyderabad </p>
            <p class="customer-details-order">8801-56 </p>
            </div>
        </div> 
         <button type="button" class="btn btn-primary edit_address">Edit address</button>
        </div>


 
    </div>
                    </div>
                        </div>
                </div>
            </section>
</div>
</div>
<div class="clearfix"></div>
