<?php
$cc= new \CoreClass();
$lb=$cc->getObject("\Core\Model\Language"); 
global $rootObj;
$wp=$rootObj;
?>
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
  <meta charset="utf-8" />
  <title>Login page</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport" />
  <meta content="" name="description" />
  <meta content="" name="author" />
  <link href="<?php echo $wp->websiteUrl; ?>assets/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
  <link href="<?php echo $wp->websiteUrl; ?>assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
  <link href="<?php echo $wp->websiteUrl; ?>css/theme/style.css" rel="stylesheet" />
   <link href="<?php echo $wp->websiteUrl; ?>css/theme/style_default.css" rel="stylesheet" />
   <link href="<?php echo $wp->websiteUrl; ?>css/theme/style_responsive.css" rel="stylesheet" />
   <link href="<?php echo $wp->websiteUrl; ?>css/theme/style_default.css" rel="stylesheet" id="style_color" />
   <link href="<?php echo $wp->websiteUrl; ?>assets/fancybox/source/jquery.fancybox.css" rel="stylesheet" />
   <script src="<?php echo $wp->websiteUrl; ?>js/theme/jquery-1.8.3.min.js"></script>
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body id="login-body">
  

  <!-- BEGIN LOGIN -->
  <div id="login">
    <div class="login-header">
      <!-- BEGIN LOGO -->
      <div id="logo" class="center" style=" color: rgb(10, 14, 114); font-size:25px;">
          Admin Panel
      </div>
      <!-- END LOGO -->
  </div>
    <!-- BEGIN LOGIN FORM -->
    <form id="loginform" name="loginform" class="form-vertical no-padding no-margin" method="post"  onsubmit="return validatelogin();">
      <div class="lock">
          <i class="icon-lock"></i>
      </div>      
      <div class="control-wrap">
          <h4>User Login</h4>
	  <div id="error_div" name="error_div" style="color: red;"></div>
          <div class="control-group">
              <div class="controls">
                  <div class="input-prepend">
                      <span class="add-on"><i class="icon-user"></i></span>
                      <input id="username" name="username" type="text" placeholder="Username" />
                      <div class="error_message" id="error_username"></div>
                  </div>
              </div>
          </div>
          <div class="control-group">
              <div class="controls">
                  <div class="input-prepend">
                      <span class="add-on"><i class="icon-key"></i></span>
                      <input id="userpassword" name="userpassword" type="password" placeholder="Password" />
                      <div class="error_message" id="error_userpassword"></div>
                  </div>
                  <div class="mtop10">
                      
                      <div class="block-hint pull-right">
                          <!--<a href="javascript:;" class="" id="forget-password">Forgot Password?</a>-->
                      </div>
                  </div>

                  <div class="clearfix space5"></div>
              </div>

          </div>
      </div>

        <input type="submit" id="login-btn" class="btn btn-block login-btn" value="Login" onclick="return validatelogin();"/>
    </form>    
    <script type="text/javascript">
       
       $("form#loginform").submit(function( event ) {           
 
  event.preventDefault();
});
      function validatelogin()
      {
          $(".error_message").html("");
        var formdata = $("form" ).serialize();
	$.ajax({
		url : "<?php echo $wp->websiteAdminUrl; ?>core_users/validateLogin",
		type : "POST",
		dataType : "html",
		data : formdata,
		success : function (responseData)
		{                     
                    var idname="#error_message";      
                    console.log(responseData);
                    $(idname).html(responseData);
                    var obj = jQuery.parseJSON(responseData)
                    if(obj.status=='success')
                    {
                        window.location.replace(obj.redirecturl);
                    }   
                    else
                    {
                        var errorsArray=obj.errors;
                        $.each(errorsArray, function(key, errorMessage) 
                        {
                            try
                            {
                                var idname="#error_"+key;                                                    
                                $(idname).html(errorMessage).show().fadeOut( 1500 );                                                  
                            }
                            catch(e)
                            {
                                console.log(e);

                            }
                        });
                    }
		}
	});
      }
    </script> 
    <!-- END LOGIN FORM -->     
    
  </div>
  <!-- END LOGIN -->
  <!-- BEGIN COPYRIGHT -->
  
  <!-- END COPYRIGHT -->
  <!-- BEGIN JAVASCRIPTS -->
  
  <script src="<?php echo $wp->websiteUrl; ?>assets/bootstrap/js/bootstrap.min.js"></script>
  <script src="<?php echo $wp->websiteUrl; ?>js/theme/scripts.js"></script>  
  <!-- END JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>