<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <div class="widget">
                    
                    <div class="widget-body" >
                        <?php                            
                            $this->loadChildBlock();
                        ?>
                    </div>
            </div>
        </div>
    </div>
</div>