<div class="container-fluid">
       
        <div class="row-fluid">	
            <div class="span12">
                <div class="widget">
                    <div class="widget-title">
                        <h4><i class="icon-reorder"></i> No Action</h4>
                        <span class="tools">
                            <a href="javascript:;" class="icon-chevron-down"></a>
                        </span>
                    </div>
                    <div class="widget-body"> 
                        Please Check Action Code Of <u> <?php echo $this->getLabel($this->_nodeName); ?></u> Action is :: <u><?php echo $this->getLabel($this->_currentAction); ?></u>
                    </div>
                </div>
            </div>
        
    </div>
</div>
