<form id="result_<?php echo $this->_nodeName;?>" name="result_<?php echo $this->_nodeName;?>">   
    <input type="hidden" id="parentformNode" name="parentformNode" value="<?php echo $this->_parentNode;?>">
   <input type="hidden" id="parentformvalue" name="parentformvalue" value="<?php echo $this->_parentSelector;?>">
   <input type="hidden" id="parentformAction" name="parentformAction" value="<?php echo $this->_parentAction;?>">
   <input type="hidden" id="action" name="action" value="save">
   <input type="hidden" id="node" name="node" value="<?php echo $this->_nodeName;?>">
   <input type="hidden" id="module" name="module" value="<?php echo $this->_currentNodeModule;?>">
</form>
   <form id="<?php echo $this->_nodeName;?>" name="<?php echo $this->_nodeName;?>"> 
   <input type="hidden" id="parentformNode" name="parentformNode" value="<?php echo $this->_parentNode;?>">
   <input type="hidden" id="parentformvalue" name="parentformvalue" value="<?php echo $this->_parentSelector;?>">
   <input type="hidden" id="parentformAction" name="parentformAction" value="<?php echo $this->_parentAction;?>">
   <input type="hidden" id="action" name="action" value="save">
   <input type="hidden" id="node" name="node" value="<?php echo $this->_nodeName;?>">
   <input type="hidden" id="module" name="module" value="<?php echo $this->_currentNodeModule;?>">
   <input type="hidden" id="accesssave" name="accesssave" value="1">
   <div id="error_div">
   </div>
   <?php
    if($this->_parentAction!='view')
    {
        ?>
   <div class="actionslist">
       <a href="javascript:void(0);">
      </a><a href="javascript:void(0);" class="btn btn-mini btn-primary" onclick="checkaction('userpermissionnodes',true,'class');">Check All</a>
      <a href="javascript:void(0);" class="btn btn-mini btn-warning" onclick="checkaction('userpermissionnodes',false,'class');">Un Check All</a>
   </div>
   
    <?php
    }
       // echo "<pre>"; print_r($this->_profileAccess); echo "</pre>";
        if(count($this->_profileAccess->_rootModules)>0)
        {
            foreach($this->_profileAccess->_rootModules as $rootmoduledata)
            {
                if(key_exists($rootmoduledata['nodename'],$this->_profileAccess->_moduleList))
                {
                    $root=$rootmoduledata['nodename'];
                    $rootdata=$this->_profileAccess->_menuItems[$root];
                    $i=1;
                    ?>
                     <div class="accordion collapse" id="accordion_<?php echo $root; ?>" style="height: auto;">
                        <div class="accordion-group">
                           <div class="accordion-heading" style="text-align: center;">
                              <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion3" href="#collapse_<?php echo $root; ?>">
                              <?php echo $this->_profileAccess->_nodeDisplay[$root]; ?>
                              </a>
                           </div>
                            <div id="collapse_<?php echo $root; ?>" class="accordion-body collapse" style="height:0;">
                                <div class="accordion-inner">
                                    <?php
                                    foreach($rootdata as $moduledisplay=>$moduledata)
                                    {
                                        
                                    
                                    ?>
                                   <div class="accordion-group">
                                      <div class="accordion-heading">
                                         <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion_<?php echo $root; ?>_<?php echo $moduledisplay; ?>" href="#collapse_<?php echo $root; ?>_<?php echo $moduledisplay; ?>">
                                         <?php echo $this->_profileAccess->_nodeDisplay[$moduledisplay]; ?>
                                         </a>
                                      </div>
                                      <div id="collapse_<?php echo $root; ?>_<?php echo $moduledisplay; ?>" class="accordion-body collapse" style="height:auto;">
                                         <div class="accordion-inner">
                                            <?php
                                                foreach($moduledata as $module=>$nodedata)
                                                {
                                                    foreach($nodedata as $node=>$action)
                                                    {
                                                        $ActionData=$this->_profileAccess->_accessbleNode[$node];
                                                        $action_name_code=$ActionData['action_name_code'];
                                                        if($action_name_code)
                                                        {
                                                            $action_name_code_list=  explode(",", $action_name_code);
                                                            
                                            ?>                                                
                                            <div class="accordion-group">
                                               <div class="accordion-heading">
                                                  <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion<?php echo $root."_".$moduledisplay."_".$node; ?>" href="#collapse<?php echo $root."_".$moduledisplay."_".$node; ?>">
                                                  <?php echo $this->_profileAccess->_nodeDisplay[$node]; ?>
                                                  </a>
                                               </div>
                                                <?php
                                                if($this->_parentAction!='view')
                                                {
                                                    ?>
                                                
                                               <div class="actionslist">
                                                  <a href="javascript:void(0);" class="btn btn-mini btn-primary" onclick="checkaction('<?php echo $node; ?>',true);">Check All</a>
                                                  <a href="javascript:void(0);" class="btn btn-mini btn-warning" onclick="checkaction('<?php echo $node; ?>',false);">Un Check All</a>
                                               </div>
                                                <?php
                                                }
                                                ?>
                                               <div id="collapse<?php echo $root."_".$moduledisplay."_".$node; ?>" class="accordion-body collapse" style="height:auto;">
                                                  <div class="accordion-inner">
                                                      <?php
                                                            $existingData=$this->_existingRecord[$node];
                                                            $existingData_Actions=  explode("|", $existingData['action']);
                                                            
                                                            foreach ($action_name_code_list as $nameWithCode)
                                                            {
                                                                $checked="";
                                                                $type="checkbox";
                                                                $style="";
                                                                if($this->_parentAction=='view')
                                                                {
                                                                    $style='style="display:none;"';
                                                                    $type="hidden";
                                                                }
                                                                $nameWithCode=explode("||",$nameWithCode);
                                                                if(in_array($nameWithCode[1],$existingData_Actions))
                                                                {
                                                                    $checked=" checked ";
                                                                }
                                                                
                                                            ?>
                                                                <div <?php echo $style; ?> class="checker" id="uniform-<?php echo $node; ?>_<?php echo $nameWithCode[1];?>">
                                                                    <span>
                                                                        <input type="<?php echo $type; ?>" class="userpermissionnodes" id="<?php echo $node; ?>_<?php echo $nameWithCode[1];?>" name="<?php echo $node; ?>[]" value="<?php echo $nameWithCode[1];?>" <?php echo $checked; ?>  >
                                                                    </span>
                                                                </div>
                                                     <?php echo $nameWithCode[0];?>,
                                                            <?php
                                                            }
                                                      ?>
                                                    
                                                  </div>
                                               </div>
                                            </div>  
                                             <?php
                                                        }
                                                    }
                                    
                                                }
                                             ?>
                                         </div>
                                      </div>
                                   </div>
                                    <?php
                                        }
                                    ?>
                                </div>
                            </div>
                        </div>
                     </div>
                    <?php
                }
            }
        }
    ?>   
    <div class="form-actions" style="text-align: center;">
        <button type="button" id="access_save" class="btn btn-small btn-success formsubmit" onclick="return getformsubmit('<?php echo $this->_nodeName; ?>','save');">Save</button>
    </div>
   </form>