<?php $wp = $this->_websiteSettings; ?>
<!-- main grid part -->
<div class="row contact">
    <section class="container" id="container-block"> 
        <div class="col-md-6 col-md-offset-3">
            <div class="row contact ">
            <h1> Login </h1>
            <div class="basic-form">
                <form class="form-horizontal" id="FormCustomerlogin">                             
                    <div class="form-group">
                        <label for="email" class="control-label">Email</label>
                            <input type="text" class="form-control" id="cutomer_email" name="cutomer_email" placeholder="Email">
                            <span class="errors" id="error_cutomer_email" style="display: none;"></span> </div> 
                    <div class="form-group">
                        <label for="phone" class="control-label">Password</label>                        
                            <input type="password" class="form-control" id="cutomer_password" name="cutomer_password" placeholder="Password">
                            <span class="errors" id="error_cutomer_password" style="display: none;"></span> </div> 
                       <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="button" class="btn btn-default pull-right" onclick="(function () {
                                        require('Customer/customer').cutomerLogin()
                                    })()">Submit</button>
                        </div>
                    </div>               
                </form>
            </div>
            </div>
        </div>
    </section>
</div>
 <script>
    require(['config'], function () {
        require(['jquery', 'contactus'], function ($) {
        });
    });
</script>