<?php
    $wp = $this->_websiteSettings;
    $session=new \Core\Session();
    $sessionData = $session->getFrontendSession();
    $customerId=$sessionData['profileId'];
?>

<!-- contant part -->
<div class="row">
    <section class="row" id="container-block">
        <section class="row">       
            <!-- Page navogation part -->
            <div class="container">
                <div class="page-navigation">
                    <ul class="breadcrumbs">
                        <li> <a href="javascript:void(0)">Home</a> </li>
                        <li> <a href="javascript:void(0)">Account</a> </li>
                        <li> <a href="javascript:void(0)">Change Password</a> </li>
                    </ul>
                </div>
            </div>
        </section>
        <section class="row account-info">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 col-md-12">
                        <?php $this->loadChildBlock("usermenu"); ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12">
                        <div class="row innerWrapper">
                            <h1 class="block-title">Change Password</h1>
                            <div class="basic-form">
                                <form id="FormChangePassword">
                                    <div class="col-md-6 col-sm-6 col-xs-12">               
                                        <div class="form-group">
                                            <label for="firstname">Current Password</label>
                                            <input type="password" class="form-control" id="cur_password" name="cur_password" placeholder="Current Password">
                                            <span class="errors" id="error_cur_password" style="display: none;"></span> </div>
                                        <div class="form-group">
                                            <label for="lastname">New Password</label>
                                            <input type="password" class="form-control" id="new_password" name="new_password" placeholder="New Password">
                                            <span class="errors" id="error_new_password" style="display: none;"></span> </div>			 
                                        <div class="form-group">
                                            <label for="company">Confirm Password</label>
                                            <input type="password" class="form-control" id="conf_password" name="conf_password" placeholder="Confirm Password">
                                            <span class="errors" id="error_conf_password" style="display: none;"></span> </div>

                                    </div>               
                                    <div class="col-md-12">
                                        <button type="button" class="btn btn-default btn-blue" onclick="(function() {require('Customer/customer').cutomerPasswordChange() })()">Change Password</button>
                                    </div>
                                </form>
                            </div>              
                        </div>
                    </div>
                    <!--/row end--> 

                </div>
            </div>
        </section>
    </section>
</div>
<!-- End contant part --> 