<?php $wp = $this->_websiteSettings; ?>
<!-- main grid part -->
<div class="row contact">
    <section class="container" id="container-block"> 
        <div class="col-md-6 col-md-offset-3">
            <div class="row contact ">
            <h1> Contact Us </h1>
            <div class="form-contact">
                <form id="FormContactUs">                             
                    <div class="form-group">
                        <label for="firstname" class="control-label">Name</label>                        
                            <input type="text" class="form-control" id="contact_name" name="contact_name" placeholder="First Name">
                            <span class="errors" id="error_contact_name" style="display: none;"></span></div>                    
                    <div class="form-group">
                        <label for="email" class="control-label">Email</label>
                            <input type="text" class="form-control" id="contact_email" name="contact_email" placeholder="Email">
                            <span class="errors" id="error_contact_email" style="display: none;"></span> </div> 
                    <div class="form-group">
                        <label for="phone" class="control-label">Phone</label>                        
                            <input type="text" class="form-control" id="contact_phone" name="contact_phone" placeholder="Phone Name">
                            <span class="errors" id="error_contact_phone" style="display: none;"></span> </div>                    
                    <div class="form-group">
                        <label for="lastname" class="control-label">Message</label>
                            <textarea rows="5" class="form-control" id="contact_message" name="contact_message" placeholder="Message" ></textarea>
                            <span class="errors" id="error_contact_message" style="display: none;"></span></div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="button" class="btn btn-default pull-right" onclick="(function () {
                                        require('Cms/contactus').contactDetails()
                                    })()">Submit</button>
                        </div>
                    </div>               
                </form>
            </div>
            </div>
        </div>
    </section>
</div>
 <script>
    require(['config'], function () {
        require(['jquery', 'contactus'], function ($) {
        });
    });
</script>