

	
		<!-- JavaScript files placed at the end of the document so the pages load faster
		================================================== -->
		<!-- Jquery and Bootstap core js files -->
		<script type="text/javascript" src="<?php echo $this->_websiteSettings->websiteUrl;?>pages/frontend/default/plugins/jquery.min.js"></script>
		<script type="text/javascript" src="<?php echo $this->_websiteSettings->websiteUrl;?>pages/frontend/default/bootstrap/js/bootstrap.min.js"></script>

		<!-- Modernizr javascript -->
		<script type="text/javascript" src="<?php echo $this->_websiteSettings->websiteUrl;?>pages/frontend/default/plugins/modernizr.js"></script>

		<!-- jQuery REVOLUTION Slider  -->
		<script type="text/javascript" src="<?php echo $this->_websiteSettings->websiteUrl;?>pages/frontend/default/plugins/rs-plugin/js/jquery.themepunch.tools.min.js"></script>
		<script type="text/javascript" src="<?php echo $this->_websiteSettings->websiteUrl;?>pages/frontend/default/plugins/rs-plugin/js/jquery.themepunch.revolution.min.js"></script>

		<!-- Isotope javascript -->
		<script type="text/javascript" src="<?php echo $this->_websiteSettings->websiteUrl;?>pages/frontend/default/plugins/isotope/isotope.pkgd.min.js"></script>

		<!-- Owl carousel javascript -->
		<script type="text/javascript" src="<?php echo $this->_websiteSettings->websiteUrl;?>pages/frontend/default/plugins/owl-carousel/owl.carousel.js"></script>

		<!-- Magnific Popup javascript -->
		<script type="text/javascript" src="<?php echo $this->_websiteSettings->websiteUrl;?>pages/frontend/default/plugins/magnific-popup/jquery.magnific-popup.min.js"></script>

		<!-- Appear javascript -->
		<script type="text/javascript" src="<?php echo $this->_websiteSettings->websiteUrl;?>pages/frontend/default/plugins/jquery.appear.js"></script>

		<!-- Count To javascript -->
		<script type="text/javascript" src="<?php echo $this->_websiteSettings->websiteUrl;?>pages/frontend/default/plugins/jquery.countTo.js"></script>

		<!-- Parallax javascript -->
		<script src="<?php echo $this->_websiteSettings->websiteUrl;?>pages/frontend/default/plugins/jquery.parallax-1.1.3.js"></script>

		<!-- Contact form -->
		<script src="<?php echo $this->_websiteSettings->websiteUrl;?>pages/frontend/default/plugins/jquery.validate.js"></script>

		<!-- SmoothScroll javascript -->
		<script type="text/javascript" src="<?php echo $this->_websiteSettings->websiteUrl;?>pages/frontend/default/plugins/jquery.browser.js"></script>
		<script type="text/javascript" src="<?php echo $this->_websiteSettings->websiteUrl;?>pages/frontend/default/plugins/SmoothScroll.js"></script>

		<!-- Initialization of Plugins -->
		<script type="text/javascript" src="<?php echo $this->_websiteSettings->websiteUrl;?>pages/frontend/default/js/js/template.js"></script>

		<!-- Custom Scripts -->
		<script type="text/javascript" src="<?php echo $this->_websiteSettings->websiteUrl;?>pages/frontend/default/js/js/custom.js"></script>

	</body>
</html>
