<!DOCTYPE html>
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if gt IE 9]> <html lang="en" class="ie"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
	<head>
		<meta charset="utf-8">
		<title>Ramesh Naidu Polarapu</title>
		<meta name="description" content="Integrations for E-commers">
		<meta name="author" content="htmlcoder.me">

		<!-- Mobile Meta -->
		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<!-- Favicon -->
		<link rel="shortcut icon" href="images/favicon.ico">

		<!-- Web Fonts -->
		<link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,700,300&amp;subset=latin,latin-ext' rel='stylesheet' type='text/css'>
		<link href='http://fonts.googleapis.com/css?family=PT+Serif' rel='stylesheet' type='text/css'>

		<!-- Bootstrap core CSS -->
		<link href="<?php echo $this->_websiteSettings->websiteUrl;?>pages/frontend/default/css/bootstrap/css/bootstrap.css" rel="stylesheet">

		<!-- Font Awesome CSS -->
		<link href="<?php echo $this->_websiteSettings->websiteUrl;?>pages/frontend/default/css/fonts/font-awesome/css/font-awesome.css" rel="stylesheet">

		<!-- Fontello CSS -->
		<link href="<?php echo $this->_websiteSettings->websiteUrl;?>pages/frontend/default/css/fonts/fontello/css/fontello.css" rel="stylesheet">

		<!-- Plugins -->
		<link href="<?php echo $this->_websiteSettings->websiteUrl;?>pages/frontend/default/plugins/rs-plugin/css/settings.css" media="screen" rel="stylesheet">
		<link href="<?php echo $this->_websiteSettings->websiteUrl;?>pages/frontend/default/plugins/rs-plugin/css/extralayers.css" media="screen" rel="stylesheet">
		<link href="<?php echo $this->_websiteSettings->websiteUrl;?>pages/frontend/default/plugins/magnific-popup/magnific-popup.css" rel="stylesheet">
		<link href="<?php echo $this->_websiteSettings->websiteUrl;?>pages/frontend/default/css/animations.css" rel="stylesheet">
		<link href="<?php echo $this->_websiteSettings->websiteUrl;?>pages/frontend/default/plugins/owl-carousel/owl.carousel.css" rel="stylesheet">

		<!-- iDea core CSS file -->
		<link href="<?php echo $this->_websiteSettings->websiteUrl;?>pages/frontend/default/css/style.css" rel="stylesheet">

		<!-- Color Scheme (In order to change the color scheme, replace the red.css with the color scheme that you prefer)-->
		<link href="<?php echo $this->_websiteSettings->websiteUrl;?>pages/frontend/default/css/skins/red.css" rel="stylesheet">

		<!-- Custom css -->
		<link href="css/custom.css" rel="stylesheet">

		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
	</head>

	<!-- body classes: 
			"boxed": boxed layout mode e.g. <body class="boxed">
			"pattern-1 ... pattern-9": background patterns for boxed layout mode e.g. <body class="boxed pattern-1"> 
	-->
	<body class="front no-trans">
		<!-- scrollToTop -->
		<!-- ================ -->
		<div class="scrollToTop"><i class="icon-up-open-big"></i></div>

