<?php 
$wp = $this->_websiteSettings; 
$session = new \Modules\Session\CustomerSession();
$sessionData = $session->getCustomerSession();
$customerId = $sessionData->getCustomerSessionId();
$locationName = $sessionData->getCustomerLocation()." ".$sessionData->getCustomerCity();
?>
<section class="theme-header header-block">
  <div class="header-block-left">
    <div class="logo header-item"><a href="home.html"> <span class="logo-sm"> Z</span> <span class="logo-lg"> ZETOE </span> </a></div>
    <div class="header-location header-item dropdown">
        <div data-toggle="dropdown" class="row btn btn-default dropdown-toggle" id="user_location">
            <p class="header-location-label">Your Location</p>
            <a href="javascript:void(0)" class="header-location-name"><?php echo substr($locationName, 0, 21); ?></a> 
        </div>
        <ul class="dropdown-menu" role="location" aria-labelledby="user_location">
            <form class="formLocationSearch">
                <p id="search-header">Search another location</p>
                <div class="form-group">
                    <div class="col-sm-9 no-padding">
                      <input type="text" onkeyup="(function() { require('Cms/customerLocation').searchDeliverLocation() })()" class="form-control" id="search_area" placeholder="Enter delivery location (Area, Street or Landmark)">
                    </div>
                    <div class="col-sm-3 no-padding">
                        <button type="button" name="btn-location" id="btnLocation">Proceed</button>
                    </div>
                </div>
                <div class="errors" id="error_search_area"></div>
                <ul id="listAreas">
                    
                </ul>
            </form>
        </ul>
    </div>
  </div>
  <div class="header-item-search">
    <div class="row header-search-bar">
      <div class="form-group">
        <div class="col-xs-10 col-sm-11 no-padding">
          <input type="text" class="form-control" id="inputEmail3" placeholder="Enter keywords to search....">
        </div>
        <div class="col-xs-2 col-sm-1 no-padding">
          <button type="button" class="btn btn-default"><i class="fa fa-search" aria-hidden="true"></i></button>
        </div>
      </div>
    </div>
  </div>
  <div class="header-block-right">
      <div class=" account header-item" id="user_info"> </div>
      <div class="cart header-item cart-toggle" id="minicart"  onclick="(function() { require('Quote/tocart').refreshCartList() })()"> 
        
    </div>
  </div>
</section>
<div class="cart-sidebar" id="cartlist"></div>
<div class="clearfix clear-header"></div>
<?php
if($customerId > 0){
    echo "<script>
    require(['config'], function () {
        require(['jquery', 'cusromerInfo'], function ($) {
        });
    });
</script>";
}  else {
    echo "<script>
    require(['config'], function () {
        require(['jquery', 'checkCusromerAuth'], function ($) {
        });
    });
</script>";
}
?>
<script>
    require(['config'], function () {
        require(['jquery', 'tocart'], function ($) {
        });
    });
</script>
<script>
    require(['config'], function () {
        require(['jquery', 'customerLocation'], function ($) {
        });
    });
</script>