<div class="clear-fix"></div>
<div class="row">
    <div class="container">
        <!-- Page navogation part -->
        <div class="page-navigation">
            <ul class="breadcrumbs">
                <li> <a href="javascript:void(0)">Home</a> </li>
                <li> <a href="javascript:void(0)">Grocery Shop</a> </li>
                <li> <a href="javascript:void(0)">Vender List</a> </li>
            </ul>
        </div>
    </div>
</div>