<?php $wp = $this->_websiteSettings; ?>
<div class="account-menu">
    <ul>
        <li class="active"><a href="<?php echo $wp->websiteUrl;  ?>ec_delivery_boy_details/dashboard"><span><i class="fa fa-th" aria-hidden="true"></i></span>Dashboard</a></li>
        <li><a href="<?php echo $wp->websiteUrl;  ?>ec_delivery_boy_details/deliverydetails"><span><i class="fa fa-calendar"></i></span>Delivery Details</a></li>
        <li><a href="<?php echo $wp->websiteUrl;  ?>ec_delivery_boy_details/deliveryhistory"><span><i class="fa fa-history" aria-hidden="true"></i></span>Delivery History</a></li>
        <li><a href="<?php echo $wp->websiteUrl;  ?>ec_delivery_boy_details/view"><span><i class="fa fa-edit"></i></span>Profile</a></li>
        <li><a href="<?php echo $wp->websiteUrl;  ?>ec_delivery_boy_details/locationdetails"><span><i class="fa fa-map-marker"></i></span>Location Details</a></li>

        
    </ul>
</div>