<?php $wp = $this->_websiteSettings; ?>
<div class="col-md-12" >
    <div class="row ven_ord_info">
    <h1>Order Details</h1>
    <div class="ven_ord_view">
        <h1>Order Id: #ORD0001</h1>
        <h1>Order Status: Pending</h1>
        <h3>Placed On: 10th March 2017 </h3>
        <div class="ord_pro_list">
             <table class="table table-bordered table-responsive">
                    <thead>
                        <tr>
                            <th>Product Image</th>
                            <th>Product Name</th>                                            
                            <th>Unit Price</th>
                            <th>Quantity</th>
                            <th>Discount</th> 
                            <th>Subtotal</th> 
                        </tr>
                    </thead>     
                    <tbody> 
                        <tr> 
                            <td><img src="<?php echo $wp->websiteUrl; ?>uploads/zetoe/carrot.png"></td>
                            <td>Carrot</td> 
                            <td>15</td> 
                            <td>2</td> 
                            <td>0.00</td>
                            <td>Rs 30</td>                            
                        </tr> 
                        <tr> 
                            <td><img src="<?php echo $wp->websiteUrl; ?>uploads/zetoe/carrot.png"></td>
                            <td>Carrot</td> 
                            <td>15</td> 
                            <td>2</td> 
                            <td>0.00</td>
                            <td>Rs 30</td>                            
                        </tr>
                         <tr> 
                            <td><img src="<?php echo $wp->websiteUrl; ?>uploads/zetoe/carrot.png"></td>
                            <td>Carrot</td> 
                            <td>15</td> 
                            <td>2</td> 
                            <td>0.00</td>
                            <td>Rs 30</td>                            
                        </tr>
                         <tr> 
                            <td><img src="<?php echo $wp->websiteUrl; ?>uploads/zetoe/carrot.png"></td>
                            <td>Carrot</td> 
                            <td>15</td> 
                            <td>2</td> 
                            <td>0.00</td>
                            <td>Rs 30</td>                            
                        </tr>
                         <tr> 
                            <td><img src="<?php echo $wp->websiteUrl; ?>uploads/zetoe/carrot.png"></td>
                            <td>Carrot</td> 
                            <td>15</td> 
                            <td>2</td> 
                            <td>0.00</td>
                            <td>Rs 30</td>                            
                        </tr>
                    </tbody> 

                </table>
        </div>
    </div>
    </div>
</div>

<script>
  require([
     'css!../css/Vendor/vendorportal/vendororder',
  ], function () {  
  });
</script>