<div class="col-md-12" >
    <div class="row ven_ord_info">
    <h1>Order List</h1>
    <div class="ven_ord_list">
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#order_list" aria-controls="order_list" role="tab" data-toggle="tab">Orderslist</a></li>
        <li role="presentation"><a href="#success_orders" aria-controls="success_orders" role="tab" data-toggle="tab">Success orders</a></li>
        <li role="presentation"><a href="#pending_orders" aria-controls="pending_orders" role="tab" data-toggle="tab">Pending Orders</a></li>
        <li role="presentation"><a href="#cancel_orders" aria-controls="cancel_orders" role="tab" data-toggle="tab">Cancel Orders</a></li>
        <li role="presentation"><a href="#return_orders" aria-controls="return_orders" role="tab" data-toggle="tab">Return Orders</a></li>
    </ul>
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="order_list">
            <div class="row">
                <table class="table table-bordered table-responsive">
                    <thead>
                        <tr>
                            <th>Order Id</th>
                            <th>Customer</th>                                            
                            <th>Payment Status</th>
                            <th>Shipping Status</th>
                            <th>Order Date</th> 
                            <th>Total</th>
                            <th>Order Status</th> 
                            <th>View</th> 
                        </tr>
                    </thead>     
                    <tbody> 
                        <tr> 
                            <td>#ORD001</td>
                            <td>Siva Kumar</td> 
                            <td><span class="complete">Completed</span></td> 
                            <td>Delivered</td> 
                            <td>10/03/207</td>
                            <td>Rs 500</td> 
                            <td><span class="complete">Completed</span></td>
                            <td><a class="order_view" href="ec_vendor/orderview">View</a></td> 
                        </tr> 
                       <tr> 
                            <td>#ORD001</td>
                            <td>Siva Kumar</td> 
                            <td><span class="pending">Pending</span></td> 
                            <td>Delivered</td> 
                            <td>10/03/207</td>
                            <td>Rs 500</td> 
                            <td><span class="pending">Pending</span></td>
                            <td><a class="order_view" href="ec_vendor/orderview">View</a></td> 
                        </tr> 
                        <tr> 
                            <td>#ORD001</td>
                            <td>Siva Kumar</td> 
                            <td><span class="processing">Processing</span></td> 
                            <td>Delivered</td> 
                            <td>10/03/207</td>
                            <td>Rs 500</td> 
                            <td><span class="cancel">Canceled</span></td>
                            <td><a class="order_view" href="ec_vendor/orderview">View</a></td> 
                        </tr>  
                        <tr> 
                            <td>#ORD001</td>
                            <td>Siva Kumar</td> 
                            <td><span class="failed">Failed</span></td> 
                            <td>Delivered</td> 
                            <td>10/03/207</td>
                            <td>Rs 500</td> 
                            <td><span class="complete">Completed</span></td>
                            <td><a class="order_view" href="ec_vendor/orderview">View</a></td> 
                        </tr> 
                        <tr> 
                            <td>#ORD001</td>
                            <td>Siva Kumar</td> 
                            <td><span class="complete">Completed</span></td> 
                            <td>Delivered</td> 
                            <td>10/03/207</td>
                            <td>Rs 500</td> 
                            <td><span class="complete">Completed</span></td>
                            <td><a class="order_view" href="ec_vendor/orderview">View</a></td> 
                        </tr>  
                    </tbody> 

                </table>
            </div>

        </div>
        <div role="tabpanel" class="tab-pane" id="success_orders">
             <div class="row">
                <table class="table table-bordered table-responsive">
                    <thead>
                        <tr>
                            <th>Order Id</th>
                            <th>Customer</th>                                            
                            <th>Payment Status</th>
                            <th>Shipping Status</th>
                            <th>Order Date</th> 
                            <th>Total</th>
                            <th>Order Status</th> 
                            <th>View</th> 
                        </tr>
                    </thead>     
                    <tbody> 
                        <tr> 
                            <td>#ORD001</td>
                            <td>Siva Kumar</td> 
                            <td><span class="complete">Completed</span></td> 
                            <td>Delivered</td> 
                            <td>10/03/207</td>
                            <td>Rs 500</td> 
                            <td><span class="complete">Completed</span></td>
                            <td><a class="order_view" href="ec_vendor/orderview">View</a></td> 
                        </tr> 
                       <tr> 
                            <td>#ORD001</td>
                            <td>Siva Kumar</td> 
                            <td><span class="complete">Completed</span></td> 
                            <td>Delivered</td> 
                            <td>10/03/207</td>
                            <td>Rs 500</td> 
                            <td><span class="complete">Completed</span></td>
                            <td><a class="order_view" href="ec_vendor/orderview">View</a></td> 
                        </tr> 
                        <tr> 
                            <td>#ORD001</td>
                            <td>Siva Kumar</td> 
                            <td><span class="complete">Completed</span></td> 
                            <td>Delivered</td> 
                            <td>10/03/207</td>
                            <td>Rs 500</td> 
                            <td><span class="complete">Completed</span></td>
                            <td><a class="order_view" href="ec_vendor/orderview">View</a></td> 
                        </tr> 
                        <tr> 
                            <td>#ORD001</td>
                            <td>Siva Kumar</td> 
                            <td><span class="complete">Completed</span></td> 
                            <td>Delivered</td> 
                            <td>10/03/207</td>
                            <td>Rs 500</td> 
                            <td><span class="complete">Completed</span></td>
                            <td><a class="order_view" href="ec_vendor/orderview">View</a></td> 
                        </tr> 
                        <tr> 
                            <td>#ORD001</td>
                            <td>Siva Kumar</td> 
                            <td><span class="complete">Completed</span></td> 
                            <td>Delivered</td> 
                            <td>10/03/207</td>
                            <td>Rs 500</td> 
                            <td><span class="complete">Completed</span></td>
                            <td><a class="order_view" href="ec_vendor/orderview">View</a></td> 
                        </tr> 
                        <tr> 
                            <td>#ORD001</td>
                            <td>Siva Kumar</td> 
                            <td><span class="complete">Completed</span></td> 
                            <td>Delivered</td> 
                            <td>10/03/207</td>
                            <td>Rs 500</td> 
                            <td><span class="complete">Completed</span></td>
                            <td><a class="order_view" href="ec_vendor/orderview">View</a></td> 
                        </tr> 
                    </tbody> 

                </table>
            </div>
        </div>
        <div role="tabpanel" class="tab-pane" id="pending_orders">
             <div class="row">
                <table class="table table-bordered table-responsive">
                    <thead>
                        <tr>
                            <th>Order Id</th>
                            <th>Customer</th>                                            
                            <th>Payment Status</th>
                            <th>Shipping Status</th>
                            <th>Order Date</th> 
                            <th>Total</th>
                            <th>Order Status</th> 
                            <th>View</th> 
                        </tr>
                    </thead>     
                    <tbody> 
                       <tr> 
                            <td>#ORD001</td>
                            <td>Siva Kumar</td> 
                            <td><span class="pending">Pending</span></td> 
                            <td>Delivered</td> 
                            <td>10/03/207</td>
                            <td>Rs 500</td> 
                            <td><span class="pending">Pending</span></td>
                            <td><a class="order_view" href="ec_vendor/orderview">View</a></td> 
                        </tr>  
                       <tr> 
                            <td>#ORD001</td>
                            <td>Siva Kumar</td> 
                            <td><span class="pending">Pending</span></td> 
                            <td>Delivered</td> 
                            <td>10/03/207</td>
                            <td>Rs 500</td> 
                            <td><span class="pending">Pending</span></td>
                            <td><a class="order_view" href="ec_vendor/orderview">View</a></td> 
                        </tr> 
                        <tr> 
                            <td>#ORD001</td>
                            <td>Siva Kumar</td> 
                            <td><span class="pending">Pending</span></td> 
                            <td>Delivered</td> 
                            <td>10/03/207</td>
                            <td>Rs 500</td> 
                            <td><span class="pending">Pending</span></td>
                            <td><a class="order_view" href="ec_vendor/orderview">View</a></td> 
                        </tr>   
                       <tr> 
                            <td>#ORD001</td>
                            <td>Siva Kumar</td> 
                            <td><span class="pending">Pending</span></td> 
                            <td>Delivered</td> 
                            <td>10/03/207</td>
                            <td>Rs 500</td> 
                            <td><span class="pending">Pending</span></td>
                            <td><a class="order_view" href="ec_vendor/orderview">View</a></td> 
                        </tr> 
                       <tr> 
                            <td>#ORD001</td>
                            <td>Siva Kumar</td> 
                            <td><span class="pending">Pending</span></td> 
                            <td>Delivered</td> 
                            <td>10/03/207</td>
                            <td>Rs 500</td> 
                            <td><span class="pending">Pending</span></td>
                            <td><a class="order_view" href="ec_vendor/orderview">View</a></td> 
                        </tr>   
                    </tbody> 

                </table>
            </div>
        </div>
        <div role="tabpanel" class="tab-pane" id="cancel_orders">
             <div class="row">
                <table class="table table-bordered table-responsive">
                    <thead>
                        <tr>
                            <th>Order Id</th>
                            <th>Customer</th>                                            
                            <th>Payment Status</th>
                            <th>Shipping Status</th>
                            <th>Order Date</th> 
                            <th>Total</th>
                            <th>Order Status</th> 
                            <th>View</th> 
                        </tr>
                    </thead>     
                    <tbody> 
                        <tr> 
                            <td>#ORD001</td>
                            <td>Siva Kumar</td> 
                            <td><span class="processing">Processing</span></td> 
                            <td>Delivered</td> 
                            <td>10/03/207</td>
                            <td>Rs 500</td> 
                            <td><span class="cancel">Canceled</span></td>
                            <td><a class="order_view" href="ec_vendor/orderview">View</a></td> 
                        </tr>
                       <tr> 
                            <td>#ORD001</td>
                            <td>Siva Kumar</td> 
                            <td><span class="processing">Processing</span></td> 
                            <td>Delivered</td> 
                            <td>10/03/207</td>
                            <td>Rs 500</td> 
                            <td><span class="cancel">Canceled</span></td>
                            <td><a class="order_view" href="ec_vendor/orderview">View</a></td> 
                        </tr> 
                        <tr> 
                            <td>#ORD001</td>
                            <td>Siva Kumar</td> 
                            <td><span class="processing">Processing</span></td> 
                            <td>Delivered</td> 
                            <td>10/03/207</td>
                            <td>Rs 500</td> 
                            <td><span class="cancel">Canceled</span></td>
                            <td><a class="order_view" href="ec_vendor/orderview">View</a></td> 
                        </tr>  
                        <tr> 
                            <td>#ORD001</td>
                            <td>Siva Kumar</td> 
                            <td><span class="processing">Processing</span></td> 
                            <td>Delivered</td> 
                            <td>10/03/207</td>
                            <td>Rs 500</td> 
                            <td><span class="cancel">Canceled</span></td>
                            <td><a class="order_view" href="ec_vendor/orderview">View</a></td> 
                        </tr>
                        <tr> 
                            <td>#ORD001</td>
                            <td>Siva Kumar</td> 
                            <td><span class="processing">Processing</span></td> 
                            <td>Delivered</td> 
                            <td>10/03/207</td>
                            <td>Rs 500</td> 
                            <td><span class="cancel">Canceled</span></td>
                            <td><a class="order_view" href="ec_vendor/orderview">View</a></td> 
                        </tr>  
                    </tbody> 

                </table>
            </div>
        </div>
        <div role="tabpanel" class="tab-pane" id="return_orders">
             <div class="row">
                <table class="table table-bordered table-responsive">
                    <thead>
                        <tr>
                            <th>Order Id</th>
                            <th>Customer</th>                                            
                            <th>Payment Status</th>
                            <th>Shipping Status</th>
                            <th>Order Date</th> 
                            <th>Total</th>
                            <th>Order Status</th> 
                            <th>View</th> 
                        </tr>
                    </thead>     
                    <tbody> 
                        <tr> 
                            <td>#ORD001</td>
                            <td>Siva Kumar</td> 
                            <td><span class="complete">Completed</span></td> 
                            <td>Delivered</td> 
                            <td>10/03/207</td>
                            <td>Rs 500</td> 
                            <td><span class="complete">Completed</span></td>
                            <td><a class="order_view" href="ec_vendor/orderview">View</a></td> 
                        </tr> 
                       <tr> 
                            <td>#ORD001</td>
                            <td>Siva Kumar</td> 
                            <td><span class="pending">Pending</span></td> 
                            <td>Delivered</td> 
                            <td>10/03/207</td>
                            <td>Rs 500</td> 
                            <td><span class="pending">Pending</span></td>
                            <td><a class="order_view" href="ec_vendor/orderview">View</a></td> 
                        </tr> 
                        <tr> 
                            <td>#ORD001</td>
                            <td>Siva Kumar</td> 
                            <td><span class="processing">Processing</span></td> 
                            <td>Delivered</td> 
                            <td>10/03/207</td>
                            <td>Rs 500</td> 
                            <td><span class="cancel">Canceled</span></td>
                            <td><a class="order_view" href="ec_vendor/orderview">View</a></td> 
                        </tr>  
                        <tr> 
                            <td>#ORD001</td>
                            <td>Siva Kumar</td> 
                            <td><span class="failed">Failed</span></td> 
                            <td>Delivered</td> 
                            <td>10/03/207</td>
                            <td>Rs 500</td> 
                            <td><span class="complete">Completed</span></td>
                            <td><a class="order_view" href="ec_vendor/orderview">View</a></td> 
                        </tr> 
                        <tr> 
                            <td>#ORD001</td>
                            <td>Siva Kumar</td> 
                            <td><span class="complete">Completed</span></td> 
                            <td>Delivered</td> 
                            <td>10/03/207</td>
                            <td>Rs 500</td> 
                            <td><span class="complete">Completed</span></td>
                            <td><a class="order_view" href="ec_vendor/orderview">View</a></td> 
                        </tr>  
                    </tbody> 

                </table>
            </div>
        </div>
    </div>
    </div>
  </div>
</div>

<script>
  require([
     'css!../css/Vendor/vendorportal/vendororder',
  ], function () {  
  });
</script>