<?php
    
    if($this->_multiedit==1)
    {
        if(key_exists($this->_pkName."pk", $this->_record))
        {
            $primarykeyValue=$this->_record[$this->_pkName."pk"];
        }
        else
        {
            $primarykeyValue=$this->_record[$this->_pkName];
        }
        $this->_Value=$this->_record[$this->_idName.'pk'];
        ?>
        <select  id="<?php echo $this->_nodeName."_".$primarykeyValue."_".$this->_idName; ?>" name="<?php echo $this->_nodeName."_save[".$primarykeyValue."][".$this->_idName."]"; ?>" class="chosen-with-diselect " onchange="<?php echo $this->_onchange; ?>" >
       <option value="">  Select <?php echo $this->getLabel($this->_idName); ?>  </option>
       <?php
            if(count($this->_options)>0)
            {
                foreach ($this->_options as $optionData)
                {
                    $sel="";
                    if($optionData['pid']==$this->_Value)
                    {
                        $sel=" selected ";
                    }
                    ?>
                        <option value="<?php echo $optionData['pid']; ?>" <?php echo $sel; ?> >  <?php echo $optionData['pds']; ?>  </option>
                    <?php
                }
            }
        ?>
    </select>
        <?php
    }
    else
    {
        echo $this->_Value;
    }
?>