<?php
$controllerObj=$this->_controllerObj;
?>
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <div class="widget">
                <div class="widget-body">
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Change Password</h3>
                            <div class="box-tools pull-right">
                                <button class="btn btn-box-tool" data-widget="collapse"><i class="icon-chevron-down"></i></button>
                            </div>
                        </div>
                        <div class="box-body chart-responsive">
									<div class="tab-content">
											<div class="tab-pane  active " id="tab_core_users">

                                    <form name="core_users" id="core_users" class="form-horizontal form_core_users" action="" method="POST" enctype="multipart/form-data">

                                        <input type="hidden" id="node" name="node" value="core_users">
                                        <input type="hidden" id="action" name="action" value="savepassword">
                                        <input type="hidden" id="action_id" name="action_id" value="savepassword">                                         
                                        
                                        <div id="error_div" name="error_div" style="color: red;font-weight: bold;"></div>  
											
												<div class="control-group" id="row_currentpassword">
                                                    <lable class="control-label">
                                                        <span id="label_currentpassword">Current Password</span>
															<span id="req_currentpassword" style="display:display" class="">
                                                            <img src="<?php echo $controllerObj->_websiteRootHostUrl; ?>/img/required_field.gif">
                                                        </span>
                                                    </lable>
                                                    <div class="control">
                                                        <div class="controls" id="value_currentpassword">    
                                                                <input class="input-large" type="password" id="currentpassword" name="currentpassword" value="" placeholder="Current Password" onchange="" required="">
    											
                                                        </div>
                                                        <span class="error_message" id="error_currentpassword"></span>

                                                    </div>
                                                </div>
												<div class="control-group" id="row_newpassword">
                                                    <lable class="control-label">
                                                        <span id="label_newpassword">New Password</span>
															<span id="req_newpassword" style="display:display" class="">
                                                            <img src="<?php echo $controllerObj->_websiteRootHostUrl; ?>/img/required_field.gif">
                                                        </span>
                                                    </lable>
                                                    <div class="control">
                                                        <div class="controls" id="value_newpassword">    
                                                                <input class="input-large" type="password" id="newpassword" name="newpassword" value="" placeholder="New Password" onchange="" required="">
    											
                                                        </div>
                                                        <span class="error_message" id="error_newpassword"></span>

                                                    </div>
                                                </div>
												<div class="control-group" id="row_renewpassword">
                                                    <lable class="control-label">
                                                        <span id="label_renewpassword">Re-Enter Password</span>
															<span id="req_renewpassword" style="display:display" class="">
                                                            <img src="<?php echo $controllerObj->_websiteRootHostUrl; ?>/img/required_field.gif">
                                                        </span>
                                                    </lable>
                                                    <div class="control">
                                                        <div class="controls" id="value_renewpassword">    
                                                                <input class="input-large" type="password" id="renewpassword" name="renewpassword" value="" placeholder="Re -Password" onchange="" required="">
    											
                                                        </div>
                                                        <span class="error_message" id="error_renewpassword"></span>

                                                    </div>
                                                </div>
                                                
                                        <div class="form-actions">
											<button type="button" id="saveandclose" name="saveandclose" class="btn btn-small btn-success formsubmit " onclick="return getformsubmit();">Save</button>
												
                                        </div>
                                    </form>
                                </div>
							</div>    
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>