
<!-- main grid part -->
<div class="row">
    <section class="container" id="container-block"> 
        <section class="row"> 
            <!-- Page navogation part -->
            <div class="page-navigation">
                <ul class="breadcrumbs">
                    <li> <a href="javascript:void(0)">Home</a> </li>
                    <li> <a href="javascript:void(0)">Grocery Shop</a> </li>
                    <li> <a href="javascript:void(0)">Vender List</a> </li>
                </ul>
            </div>
        </section>

        <div class="row cartlist">
            <div class="container">
                <div id="product-info-table">           
                    <div class="col-md-9 col-lg-9 col-sm-7">
                    <?php $this->loadChildBlock("cartlist"); ?>
                    </div>
                    <div class="col-md-3 col-lg-3 col-sm-5" id="final_cost">
                        <div class="row" id="update_minicart">
                            <?php $this->loadChildBlock("quote_minicart"); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>  

    </section>
</div>
