<?php $wp = $this->_websiteSettings; ?>
<div class="container">
    <div class="row">
        <div class="col-lg-12 ">
            <div class="row userInfo">

                <div class="thanxContent text-center">

                    <h1> Thank you for your order <a href="order-status.html">#6469</a></h1>
                    <h4>we'll let you know when your items are on their way</h4>

                </div>

                <div class="col-lg-7 col-center">
                    <h4></h4>

                    <div class="cartContent table-responsive  w100">
                        <table style="width:100%" class="cartTable cartTableBorder">
                            <tbody id="price">

                                <tr class="CartProduct  cartTableHeader">
                                    <td colspan="2" style="line-height: 49px;"> Items to be Shipped</td>


                                    <td style="width:15%;line-height: 49px;
                                        "></td>
                                </tr>

                                <tr class="CartProduct">
                                    <td class="CartProductThumb">
                                        <div><a href=""><img alt="img" src="<?php echo $wp->websiteUrl;  ?>img/images/carrot1.jpg"></a>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="CartDescription">
                                            <h4><a href="">Denim T shirt Black </a></h4>
                                            <span class="size">12 x 1.5 L</span>

                                            <div class="price"><i class="fa fa-inr" aria-hidden="true"></i> 8.80</div>
                                        </div>
                                    </td>


                                    <td class="price"><i class="fa fa-inr" aria-hidden="true"></i> 300</td>
                                </tr>

                                <tr class="CartProduct">
                                    <td class="CartProductThumb">
                                        <div><a href=""><img alt="img" src="<?php echo $wp->websiteUrl;  ?>img/images/carrot1.jpg"></a>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="CartDescription">
                                            <h4><a href="">Denim T shirt Red </a></h4>
                                            <span class="size">12 x 1.5 L</span>

                                            <div class="price"><i class="fa fa-inr" aria-hidden="true"></i> 30</div>
                                        </div>
                                    </td>


                                    <td class="price"><i class="fa fa-inr" aria-hidden="true"></i> 60</td>
                                </tr>

                                <tr class="CartProduct">
                                    <td class="CartProductThumb">
                                        <div>
                                            <a href=""><img alt="img" src="<?php echo $wp->websiteUrl;  ?>img/images/carrot1.jpg"></a>
                                        </div>
                                    </td>

                                    <td>
                                        <div class="CartDescription">
                                            <h4><a href="">Denim T shirt Blue </a></h4>
                                            <span class="size">12 x 1.5 L</span>

                                            <div class="price"> <i class="fa fa-inr" aria-hidden="true"></i> 8.80</div>
                                        </div>
                                    </td>


                                    <td class="price"><i class="fa fa-inr" aria-hidden="true"></i> 60</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
            <!--/row end-->

        </div>

        <!--/rightSidebar-->

    </div>
</div>