<?php $wp = $this->_websiteSettings; ?>
<div class="row">
    <div class="container">
        <div class="confirm_order_block" style="margin: 230px 0px">
            <h1 style="text-align: center; margin-bottom: 15px; font-size: 45px;">Thank you for your order.</h1>
            <p style="text-align: center; color: #0db8d0; font-size: 18px;"><a href=<?php echo $wp->websiteUrl; ?>account/order-history>View your order status</a></p>
        </div>
    </div>
</div>
